In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 50)

In [ ]:
tech_sales = pd.DataFrame({
    'OrderID':[1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,
               1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030],
    'OrderDate':['2024-01-03','2024-01-04','2024-01-05','2024-01-07','2024-01-09','2024-01-10',
                 '2024-01-12','2024-01-17','2024-01-19','2024-01-21','2024-01-23','2024-01-25',
                 '2024-01-27','2024-01-29','2024-01-31','2024-02-02','2024-02-04','2024-02-06',
                 '2024-02-08','2024-02-10','2024-02-12','2024-02-14','2024-02-16','2024-02-18',
                 '2024-02-20','2024-02-22','2024-02-24','2024-02-26','2024-02-28','2024-03-01'],
    'Region':['East','West','North','South','East','West','North','East','North','West','South',
              'East','West','North','South','East','West','North','South','East','West','North',
              'South','East','West','North','South','East','West','North'],
    'Product':['Laptop','Mouse','Monitor','Keyboard','Headset','Laptop','Mouse Pad','Tablet','Webcam',
               'Speaker','Earbuds','Monitor','Mouse','Laptop','Keyboard','Headset','Tablet','Mouse Pad',
               'Webcam','Speaker','Earbuds','Laptop','Monitor','Mouse','Keyboard','Headset','Tablet',
               'Webcam','Speaker','Earbuds'],
    'Category':['Electronics','Accessories','Electronics','Accessories','Audio','Electronics','Accessories',
                'Electronics','Accessories','Audio','Audio','Electronics','Accessories','Electronics',
                'Accessories','Audio','Electronics','Accessories','Accessories','Audio','Audio',
                'Electronics','Electronics','Accessories','Accessories','Audio','Electronics','Accessories',
                'Audio','Audio'],
    'UnitPrice':[1200,25,280,45,80,1150,15,600,60,100,70,280,25,1200,45,80,600,15,60,100,70,1200,280,25,
                 45,80,600,60,100,70],
    'Quantity':[1,3,2,2,1,1,4,2,3,1,2,1,4,1,3,2,1,2,1,3,2,1,2,3,1,2,1,4,2,3],
    'Discount':[0.05,0.00,0.10,0.00,0.15,0.00,0.00,0.05,0.10,0.00,0.15,0.00,0.05,0.10,0.00,0.15,0.00,
                0.05,0.10,0.00,0.15,0.00,0.05,0.10,0.00,0.15,0.00,0.05,0.10,0.00],
    'PaymentMethod':['Card','Cash','Online','Card','Online','Card','Cash','Online','Card','Cash','Online',
                      'Card','Cash','Online','Card','Cash','Online','Card','Cash','Online','Card','Cash',
                      'Online','Card','Cash','Online','Card','Cash','Online','Card'],
    'Profit':[210,18,95,28,22,190,16,120,17,20,15,60,10,220,26,20,105,12,15,25,18,220,50,14,26,18,110,15,18,20]
})

tech_sales.to_csv('tech_sales.csv', index=False) 
print(tech_sales.shape)


## rafa3t el sora we chat 3ml el dataframe

(30, 10)

In [3]:
df1 = pd.read_csv('tech_sales.csv')
print("First 5 rows:")
print(df1.head())

print("Last 5 rows:")
print(df1.tail())

First 5 rows:
   OrderID   OrderDate Region   Product     Category  UnitPrice  Quantity  \
0     1001  2024-01-03   East    Laptop  Electronics       1200         1
1     1002  2024-01-04   West     Mouse  Accessories         25         3
2     1003  2024-01-05  North   Monitor  Electronics        280         2
3     1004  2024-01-07  South  Keyboard  Accessories         45         2
4     1005  2024-01-09   East   Headset        Audio         80         1

   Discount PaymentMethod  Profit
0      0.05          Card     210
1      0.00          Cash      18
2      0.10        Online      95
3      0.00          Card      28
4      0.15        Online      22
Last 5 rows:
    OrderID   OrderDate Region  Product     Category  UnitPrice  Quantity  \
25     1026  2024-02-22  North  Headset        Audio         80         2
26     1027  2024-02-24  South   Tablet  Electronics        600         1
27     1028  2024-02-26   East   Webcam  Accessories         60         4
28     1029  2024-02-28   West  Speaker        Audio        100         2
29     1030  2024-03-01  North  Earbuds        Audio         70         3

    Discount PaymentMethod  Profit
25      0.15        Online      18
26      0.00          Card     110
27      0.05          Cash      15
28      0.10        Online      18
29      0.00          Card      20

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        30 non-null     int64
 1   OrderDate      30 non-null     object
 2   Region         30 non-null     object
 3   Product        30 non-null     object
 4   Category       30 non-null     object
 5   UnitPrice      30 non-null     int64
 6   Quantity       30 non-null     int64
 7   Discount       30 non-null     float64
 8   PaymentMethod  30 non-null     object
 9   Profit         30 non-null     int64
dtypes: float64(1), int64(4), object(5)
memory usage: 2.5+ KB

In [ ]:
print(df1.isnull().sum())

OrderID          0
OrderDate        0
Region           0
Product          0
Category         0
UnitPrice        0
Quantity         0
Discount         0
PaymentMethod    0
Profit           0
dtype: int64

In [ ]:
df1.describe()

           OrderID    UnitPrice   Quantity  Discount      Profit
count    30.000000    30.000000  30.000000  30.00000   30.000000
mean   1015.500000   285.333333   2.033333   0.05500   58.433333
std       8.803408   398.200550   0.999425   0.05776   68.132064
min    1001.000000    15.000000   1.000000   0.00000   10.000000
25%    1008.250000    48.750000   1.000000   0.00000   17.250000
50%    1015.500000    80.000000   2.000000   0.05000   21.000000
75%    1022.750000   280.000000   3.000000   0.10000   86.250000
max    1030.000000  1200.000000   4.000000   0.15000  220.000000

In [8]:
df1[['Product','Category','UnitPrice','Quantity','Profit']].head()

    Product     Category  UnitPrice  Quantity  Profit
0    Laptop  Electronics       1200         1     210
1     Mouse  Accessories         25         3      18
2   Monitor  Electronics        280         2      95
3  Keyboard  Accessories         45         2      28
4   Headset        Audio         80         1      22

In [9]:
df1[df1['Quantity'] > 2]

,OrderID,OrderDate,Region,Product,Category,UnitPrice,Quantity,Discount,PaymentMethod,Profit
1,1002,2024-01-04,West,Mouse,Accessories,25,3,0.00,Cash,18
6,1007,2024-01-12,North,Mouse Pad,Accessories,15,4,0.00,Cash,16
8,1009,2024-01-19,North,Webcam,Accessories,60,3,0.10,Card,17
12,1013,2024-01-27,West,Mouse,Accessories,25,4,0.05,Cash,10
14,1015,2024-01-31,South,Keyboard,Accessories,45,3,0.00,Card,26
19,1020,2024-02-10,East,Speaker,Audio,100,3,0.00,Online,25
23,1024,2024-02-18,East,Mouse,Accessories,25,3,0.10,Card,14
27,1028,2024-02-26,East,Webcam,Accessories,60,4,0.05,Cash,15
29,1030,2024-03-01,North,Earbuds,Audio,70,3,0.00,Card,20

In [10]:
df1[(df1['Category'] == 'Electronics') & (df1['Profit'] > 100)]

,OrderID,OrderDate,Region,Product,Category,UnitPrice,Quantity,Discount,PaymentMethod,Profit
0,1001,2024-01-03,East,Laptop,Electronics,1200,1,0.05,Card,210
5,1006,2024-01-10,West,Laptop,Electronics,1150,1,0.00,Card,190
7,1008,2024-01-17,East,Tablet,Electronics,600,2,0.05,Online,120
13,1014,2024-01-29,North,Laptop,Electronics,1200,1,0.10,Online,220
16,1017,2024-02-04,West,Tablet,Electronics,600,1,0.00,Online,105
21,1022,2024-02-14,North,Laptop,Electronics,1200,1,0.00,Cash,220
26,1027,2024-02-24,South,Tablet,Electronics,600,1,0.00,Card,110

## DataFrame 2

In [14]:
employee_performance = pd.DataFrame({
    'EmployeeID':[101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,
                  121,122,123,124,125],
    'Name':['Ali','Sara','Mona','Omar','Nour','Hassan','Laila','Youssef','Rana','Karim','Dina','Tarek',
            'Salma','Amr','Heba','Fady','Mai','Sherif','Yara','Adel','Menna','Ziad','Aya','Bassem','Nada'],
    'Department':['IT','HR','IT','Finance','HR','Finance','IT','Finance','HR','IT','Finance','HR','IT',
                  'Finance','HR','IT','Finance','HR','IT','Finance','HR','IT','Finance','HR','IT'],
    'City':['Cairo','Alex','Cairo','Giza','Cairo','Alex','Giza','Cairo','Alex','Giza','Cairo','Alex',
            'Giza','Cairo','Alex','Giza','Cairo','Alex','Giza','Cairo','Alex','Giza','Cairo','Alex','Giza'],
    'Salary':[12000,9000,15000,13000,9500,14000,np.nan,11000,9800,12500,13500,9200,14500,10800,9600,
              12800,13900,9400,15200,11200,9700,12300,14100,9900,13200],
    'ExperienceYears':[2,5,4,6,3,7,1,4,2,5,6,3,7,2,4,5,6,3,7,2,4,5,6,3,4],
    'PerformanceScore':[85,78,92,88,73,90,69,80,75,86,89,72,91,79,76,84,87,74,93,81,77,85,90,73,82],
    'TrainingHours':[12,18,20,15,10,25,8,14,9,17,22,11,24,13,10,16,21,9,25,12,14,18,23,10,15],
    'Remote':['Yes','No','Yes','No','Yes','No','Yes','No','Yes','No','Yes','No','Yes','No','Yes','No',
              'Yes','No','Yes','No','Yes','No','Yes','No','Yes'],
    'JoinDate':['2022-01-15','2020-03-10','2021-07-01','2019-11-20','2023-02-05','2018-08-12','2024-01-10',
                '2020-05-15','2022-09-01','2019-04-20','2021-01-15','2023-06-10','2018-12-01','2022-03-20',
                '2020-10-05','2019-07-12','2021-11-10','2023-01-20','2018-05-15','2022-08-01','2020-02-10',
                '2019-09-20','2021-04-15','2023-10-10','2020-07-01']
})

employee_performance.to_csv('employee_performance.csv', index=False)
print(employee_performance.shape)

(25, 10)

In [15]:
df2 = pd.read_csv('employee_performance.csv')
print("First 5 rows:")
print(df2.head())

df2.info()

First 5 rows:
   EmployeeID  Name Department   City   Salary  ExperienceYears  \
0         101   Ali         IT  Cairo  12000.0                2
1         102  Sara         HR   Alex   9000.0                5
2         103  Mona         IT  Cairo  15000.0                4
3         104  Omar    Finance   Giza  13000.0                6
4         105  Nour         HR  Cairo   9500.0                3

   PerformanceScore  TrainingHours Remote    JoinDate
0                85             12    Yes  2022-01-15
1                78             18     No  2020-03-10
2                92             20    Yes  2021-07-01
3                88             15     No  2019-11-20
4                73             10    Yes  2023-02-05
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        25 non-null     int64
 1   Name              25 non-null     object
 2   Department        25 non-null     object
 3   City              25 non-null     object
 4   Salary            24 non-null     float64
 5   ExperienceYears   25 non-null     int64
 6   PerformanceScore  25 non-null     int64
 7   TrainingHours     25 non-null     int64
 8   Remote            25 non-null     object
 9   JoinDate          25 non-null     object
dtypes: float64(1), int64(4), object(5)
memory usage: 2.1+ KB

In [16]:
print(df2.isnull().sum())

EmployeeID          0
Name                0
Department          0
City                0
Salary              1
ExperienceYears     0
PerformanceScore    0
TrainingHours       0
Remote              0
JoinDate            0
dtype: int64

In [17]:
df2.describe()

,EmployeeID,Salary,ExperienceYears,PerformanceScore,TrainingHours
count,25.000000,24.000000,25.000000,25.000000,25.000000
mean,113.000000,11879.166667,4.240000,81.960000,15.640000
std,7.359801,2043.649584,1.762574,7.109149,5.415102
min,101.000000,9000.000000,1.000000,69.000000,8.000000
25%,107.000000,9775.000000,3.000000,76.000000,11.000000
50%,113.000000,12150.000000,4.000000,82.000000,15.000000
75%,119.000000,13600.000000,6.000000,88.000000,20.000000
max,125.000000,15200.000000,7.000000,93.000000,25.000000

In [18]:
df2[['Name','Department','Salary','PerformanceScore']].head()

   Name Department   Salary  PerformanceScore
0   Ali         IT  12000.0                85
1  Sara         HR   9000.0                78
2  Mona         IT  15000.0                92
3  Omar    Finance  13000.0                88
4  Nour         HR   9500.0                73

In [25]:
print(df2[df2['Department'] == 'IT'])

print(df2[(df2['Department'] == 'IT') & (df2['PerformanceScore'] >= 85)])

    EmployeeID   Name Department   City   Salary  ExperienceYears  \
0          101    Ali         IT  Cairo  12000.0                2
2          103   Mona         IT  Cairo  15000.0                4
6          107  Laila         IT   Giza      NaN                1
9          110  Karim         IT   Giza  12500.0                5
12         113  Salma         IT   Giza  14500.0                7
15         116   Fady         IT   Giza  12800.0                5
18         119   Yara         IT   Giza  15200.0                7
21         122   Ziad         IT   Giza  12300.0                5
24         125   Nada         IT   Giza  13200.0                4

    PerformanceScore  TrainingHours Remote    JoinDate
0                 85             12    Yes  2022-01-15
2                 92             20    Yes  2021-07-01
6                 69              8    Yes  2024-01-10
9                 86             17     No  2019-04-20
12                91             24    Yes  2018-12-01
15                84             16     No  2019-07-12
18                93             25    Yes  2018-05-15
21                85             18     No  2019-09-20
24                82             15    Yes  2020-07-01
    EmployeeID   Name Department   City   Salary  ExperienceYears  \
0          101    Ali         IT  Cairo  12000.0                2
2          103   Mona         IT  Cairo  15000.0                4
9          110  Karim         IT   Giza  12500.0                5
12         113  Salma         IT   Giza  14500.0                7
18         119   Yara         IT   Giza  15200.0                7
21         122   Ziad         IT   Giza  12300.0                5

    PerformanceScore  TrainingHours Remote    JoinDate
0                 85             12    Yes  2022-01-15
2                 92             20    Yes  2021-07-01
9                 86             17     No  2019-04-20
12                91             24    Yes  2018-12-01
18                93             25    Yes  2018-05-15
21                85             18     No  2019-09-20

In [26]:
df2[(df2['City'] == 'Cairo') | (df2['City'] == 'Alex')]

,EmployeeID,Name,Department,City,Salary,ExperienceYears,PerformanceScore,TrainingHours,Remote,JoinDate
0,101,Ali,IT,Cairo,12000.0,2,85,12,Yes,2022-01-15
1,102,Sara,HR,Alex,9000.0,5,78,18,No,2020-03-10
2,103,Mona,IT,Cairo,15000.0,4,92,20,Yes,2021-07-01
4,105,Nour,HR,Cairo,9500.0,3,73,10,Yes,2023-02-05
5,106,Hassan,Finance,Alex,14000.0,7,90,25,No,2018-08-12
7,108,Youssef,Finance,Cairo,11000.0,4,80,14,No,2020-05-15
8,109,Rana,HR,Alex,9800.0,2,75,9,Yes,2022-09-01
10,111,Dina,Finance,Cairo,13500.0,6,89,22,Yes,2021-01-15
11,112,Tarek,HR,Alex,9200.0,3,72,11,No,2023-06-10
13,114,Amr,Finance,Cairo,10800.0,2,79,13,No,2022-03-20
14,115,Heba,HR,Alex,9600.0,4,76,10,Yes,2020-10-05
16,117,Mai,Finance,Cairo,13900.0,6,87,21,Yes,2021-11-10
17,118,Sherif,HR,Alex,9400.0,3,74,9,No,2023-01-20
19,120,Adel,Finance,Cairo,11200.0,2,81,12,No,2022-08-01
20,121,Menna,HR,Alex,9700.0,4,77,14,Yes,2020-02-10
22,123,Aya,Finance,Cairo,14100.0,6,90,23,Yes,2021-04-15
23,124,Bassem,HR,Alex,9900.0,3,73,10,No,2023-10-10

In [28]:
df2.loc[0:3, ['Name','Salary','PerformanceScore']]

   Name   Salary  PerformanceScore
0   Ali  12000.0                85
1  Sara   9000.0                78
2  Mona  15000.0                92
3  Omar  13000.0                88

## DataFrame 3

In [29]:
course_progress = pd.DataFrame({
    'StudentID':[201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,
                 221,222,223,224,225,226,227,228],
    'StudentName':['Adam','Mariam','Yara','Omar','Salma','Hady','Nour','Layla','Kareem','Reem','Fadi',
                   'Dalia','Hossam','Mira','Waleed','Sherine','Amir','Farida','Nabil','Hana','Sami',
                   'Nesma','Tamer','Rawan','Bassel','Iman','Wael','Ghada'],
    'Course':['Python','Excel','Power BI','Python','SQL','Power BI','Python','Excel','SQL','Python',
              'Power BI','Excel','SQL','Python','Power BI','Excel','SQL','Python','Power BI','Excel',
              'SQL','Python','Power BI','Excel','SQL','Python','Power BI','Excel'],
    'Level':['Beginner','Beginner','Inter','Beginner','Inter','Inter','Advanced','Beginner','Inter',
             'Advanced','Beginner','Inter','Beginner','Inter','Advanced','Beginner','Inter','Beginner',
             'Inter','Advanced','Beginner','Inter','Beginner','Advanced','Inter','Beginner','Inter','Advanced'],
    'City':['Cairo','Giza','Alex','Cairo','Mansoura','Alex','Cairo','Giza','Mansoura','Cairo','Alex',
            'Giza','Mansoura','Cairo','Alex','Giza','Mansoura','Cairo','Alex','Giza','Mansoura','Cairo',
            'Alex','Giza','Mansoura','Cairo','Alex','Giza'],
    'EnrollDate':['2024-02-01','2024-02-03','2024-02-04','2024-02-06','2024-02-07','2024-02-10',
                  '2024-02-11','2024-02-13','2024-02-15','2024-02-17','2024-02-19','2024-02-21',
                  '2024-02-23','2024-02-25','2024-02-27','2024-02-29','2024-03-02','2024-03-04',
                  '2024-03-06','2024-03-08','2024-03-10','2024-03-12','2024-03-14','2024-03-16',
                  '2024-03-18','2024-03-20','2024-03-22','2024-03-24'],
    'Completed':['Yes','No','Yes','Yes','No','Yes','Yes','No','Yes','Yes','No','Yes','No','Yes','Yes',
                 'No','Yes','Yes','No','Yes','Yes','No','Yes','Yes','No','Yes','Yes','No'],
    'HoursSpent':[18,7,15,20,9,14,24,6,16,22,8,17,7,19,23,9,15,21,8,25,12,7,18,20,9,16,22,6],
    'Score':[88,54,91,95,61,84,90,58,87,93,55,89,60,86,92,57,88,94,59,96,80,56,85,91,62,89,93,53],
    'Rating':[4.8,np.nan,4.9,5.0,3.8,4.5,4.7,3.6,4.6,4.9,3.7,4.7,3.9,4.5,4.8,3.6,4.6,4.9,3.8,5.0,4.2,
              3.7,4.5,4.8,3.9,4.6,4.9,3.5],
    'CoursePrice':[120,80,150,120,100,150,180,80,100,180,150,80,100,120,180,80,100,120,150,180,100,
                   80,150,120,100,120,150,80]
})

course_progress.to_csv('course_progress.csv', index=False)
print(course_progress.shape)

(28, 11)

In [30]:
df3 = pd.read_csv('course_progress.csv')
print("First 5 rows:")
print(df3.head())

df3.describe()

First 5 rows:
   StudentID StudentName    Course     Level      City  EnrollDate Completed  \
0        201        Adam    Python  Beginner     Cairo  2024-02-01       Yes
1        202      Mariam     Excel  Beginner      Giza  2024-02-03        No
2        203        Yara  Power BI     Inter      Alex  2024-02-04       Yes
3        204        Omar    Python  Beginner     Cairo  2024-02-06       Yes
4        205       Salma       SQL     Inter  Mansoura  2024-02-07        No

   HoursSpent  Score  Rating  CoursePrice
0          18     88     4.8          120
1           7     54     NaN           80
2          15     91     4.9          150
3          20     95     5.0          120
4           9     61     3.8          100

        StudentID  HoursSpent      Score     Rating  CoursePrice
count   28.000000   28.000000  28.000000  27.000000    28.000000
mean   214.500000   14.750000  78.071429   4.385185   122.142857
std      8.225975    6.198118  16.052988   0.513438    34.249319
min    201.000000    6.000000  53.000000   3.500000    80.000000
25%    207.750000    8.750000  59.750000   3.850000   100.000000
50%    214.500000   15.500000  86.500000   4.600000   120.000000
75%    221.250000   20.000000  91.000000   4.800000   150.000000
max    228.000000   25.000000  96.000000   5.000000   180.000000

In [31]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudentID    28 non-null     int64
 1   StudentName  28 non-null     object
 2   Course       28 non-null     object
 3   Level        28 non-null     object
 4   City         28 non-null     object
 5   EnrollDate   28 non-null     object
 6   Completed    28 non-null     object
 7   HoursSpent   28 non-null     int64
 8   Score        28 non-null     int64
 9   Rating       27 non-null     float64
 10  CoursePrice  28 non-null     int64
dtypes: float64(1), int64(4), object(6)
memory usage: 2.5+ KB

In [32]:
df3[['StudentName','Course','HoursSpent','Score','Rating']]

   StudentName    Course  HoursSpent  Score  Rating
0         Adam    Python          18     88     4.8
1       Mariam     Excel           7     54     NaN
2         Yara  Power BI          15     91     4.9
3         Omar    Python          20     95     5.0
4        Salma       SQL           9     61     3.8
5         Hady  Power BI          14     84     4.5
6         Nour    Python          24     90     4.7
7        Layla     Excel           6     58     3.6
8       Kareem       SQL          16     87     4.6
9         Reem    Python          22     93     4.9
10        Fadi  Power BI           8     55     3.7
11       Dalia     Excel          17     89     4.7
12      Hossam       SQL           7     60     3.9
13        Mira    Python          19     86     4.5
14      Waleed  Power BI          23     92     4.8
15     Sherine     Excel           9     57     3.6
16        Amir       SQL          15     88     4.6
17      Farida    Python          21     94     4.9
18       Nabil  Power BI           8     59     3.8
19        Hana     Excel          25     96     5.0
20        Sami       SQL          12     80     4.2
21       Nesma    Python           7     56     3.7
22       Tamer  Power BI          18     85     4.5
23       Rawan     Excel          20     91     4.8
24      Bassel       SQL           9     62     3.9
25        Iman    Python          16     89     4.6
26        Wael  Power BI          22     93     4.9
27       Ghada     Excel           6     53     3.5

In [33]:
completed_students = df3[df3['Completed'] == 'Yes']
completed_students.head()

,StudentID,StudentName,Course,Level,City,EnrollDate,Completed,HoursSpent,Score,Rating,CoursePrice
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.8,120
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.9,150
3,204,Omar,Python,Beginner,Cairo,2024-02-06,Yes,20,95,5.0,120
5,206,Hady,Power BI,Inter,Alex,2024-02-10,Yes,14,84,4.5,150
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.7,180

In [34]:
top_students = df3[(df3['Score'] >= 85) & (df3['HoursSpent'] >= 15)]
top_students

,StudentID,StudentName,Course,Level,City,EnrollDate,Completed,HoursSpent,Score,Rating,CoursePrice
0,201,Adam,Python,Beginner,Cairo,2024-02-01,Yes,18,88,4.8,120
2,203,Yara,Power BI,Inter,Alex,2024-02-04,Yes,15,91,4.9,150
3,204,Omar,Python,Beginner,Cairo,2024-02-06,Yes,20,95,5.0,120
6,207,Nour,Python,Advanced,Cairo,2024-02-11,Yes,24,90,4.7,180
8,209,Kareem,SQL,Inter,Mansoura,2024-02-15,Yes,16,87,4.6,100
9,210,Reem,Python,Advanced,Cairo,2024-02-17,Yes,22,93,4.9,180
11,212,Dalia,Excel,Inter,Giza,2024-02-21,Yes,17,89,4.7,80
13,214,Mira,Python,Inter,Cairo,2024-02-25,Yes,19,86,4.5,120
14,215,Waleed,Power BI,Advanced,Alex,2024-02-27,Yes,23,92,4.8,180
16,217,Amir,SQL,Inter,Mansoura,2024-03-02,Yes,15,88,4.6,100
17,218,Farida,Python,Beginner,Cairo,2024-03-04,Yes,21,94,4.9,120
19,220,Hana,Excel,Advanced,Giza,2024-03-08,Yes,25,96,5.0,180
22,223,Tamer,Power BI,Beginner,Alex,2024-03-14,Yes,18,85,4.5,150
23,224,Rawan,Excel,Advanced,Giza,2024-03-16,Yes,20,91,4.8,120
25,226,Iman,Python,Beginner,Cairo,2024-03-20,Yes,16,89,4.6,120
26,227,Wael,Power BI,Inter,Alex,2024-03-22,Yes,22,93,4.9,150

In [35]:
follow_up_students = df3[(df3['Completed'] == 'No') | (df3['Score'] < 60)]
follow_up_students

,StudentID,StudentName,Course,Level,City,EnrollDate,Completed,HoursSpent,Score,Rating,CoursePrice
1,202,Mariam,Excel,Beginner,Giza,2024-02-03,No,7,54,NaN,80
4,205,Salma,SQL,Inter,Mansoura,2024-02-07,No,9,61,3.8,100
7,208,Layla,Excel,Beginner,Giza,2024-02-13,No,6,58,3.6,80
10,211,Fadi,Power BI,Beginner,Alex,2024-02-19,No,8,55,3.7,150
12,213,Hossam,SQL,Beginner,Mansoura,2024-02-23,No,7,60,3.9,100
15,216,Sherine,Excel,Beginner,Giza,2024-02-29,No,9,57,3.6,80
18,219,Nabil,Power BI,Inter,Alex,2024-03-06,No,8,59,3.8,150
21,222,Nesma,Python,Inter,Cairo,2024-03-12,No,7,56,3.7,80
24,225,Bassel,SQL,Inter,Mansoura,2024-03-18,No,9,62,3.9,100
27,228,Ghada,Excel,Advanced,Giza,2024-03-24,No,6,53,3.5,80

## DataFrame 4

In [36]:
restaurant_orders = pd.DataFrame({
    'OrderID':[301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,
               321,322,323,324,325,326,327,328,329,330,331,332],
    'OrderDate':['2024-03-01','2024-03-01','2024-03-02','2024-03-02','2024-03-03','2024-03-03',
                 '2024-03-04','2024-03-05','2024-03-06','2024-03-07','2024-03-08','2024-03-09',
                 '2024-03-10','2024-03-11','2024-03-12','2024-03-13','2024-03-14','2024-03-15',
                 '2024-03-16','2024-03-17','2024-03-18','2024-03-19','2024-03-20','2024-03-21',
                 '2024-03-22','2024-03-23','2024-03-24','2024-03-25','2024-03-26','2024-03-27',
                 '2024-03-28','2024-03-29'],
    'Meal':['Burger','Pizza','Pasta','Salad','Burger','Sushi','Pizza','Ramen','Fries','Grilled Chicken',
            'Burger','Pizza','Pasta','Salad','Sushi','Ramen','Fries','Grilled Chicken','Burger','Pizza',
            'Pasta','Salad','Sushi','Ramen','Fries','Grilled Chicken','Burger','Pizza','Pasta','Salad',
            'Sushi','Ramen'],
    'Category':['Fast Food','Italian','Italian','Healthy','Fast Food','Asian','Italian','Asian',
                'Fast Food','Healthy','Fast Food','Italian','Italian','Healthy','Asian','Asian',
                'Fast Food','Healthy','Fast Food','Italian','Italian','Healthy','Asian','Asian',
                'Fast Food','Healthy','Fast Food','Italian','Italian','Healthy','Asian','Asian'],
    'Channel':['Delivery','Dine-in','Delivery','Takeaway','Dine-in','Delivery','Delivery','Takeaway',
               'Dine-in','Delivery','Takeaway','Dine-in','Delivery','Takeaway','Dine-in','Delivery',
               'Takeaway','Dine-in','Delivery','Takeaway','Dine-in','Delivery','Takeaway','Dine-in',
               'Delivery','Takeaway','Dine-in','Delivery','Takeaway','Dine-in','Delivery','Takeaway'],
    'Quantity':[2,1,1,2,3,1,2,1,2,1,2,1,3,1,2,1,2,3,1,2,1,2,1,3,1,2,1,2,1,3,1,2],
    'UnitPrice':[8.5,12,10.5,6,8.5,16,12,14,4,11,8.5,12,10.5,6,16,14,4,11,8.5,12,10.5,6,16,14,4,11,
                 8.5,12,10.5,6,16,14],
    'Rating':[4.6,4.8,4.1,4.4,4.7,4.9,4.3,4.0,3.9,4.5,4.2,4.6,4.0,4.3,4.8,3.9,4.1,4.4,4.5,4.7,4.2,4.6,
              4.9,4.0,3.8,4.3,4.6,4.8,4.1,4.4,4.9,4.0],
    'DeliveryMinutes':[32,0,45,0,0,38,41,0,0,35,0,0,40,0,36,0,0,33,0,0,42,0,37,0,0,34,0,39,0,0,36,0],
    'PaymentMethod':['App','Card','App','Cash','Card','App','App','Cash','Card','App','Cash','Card',
                     'App','Cash','Card','App','Cash','Card','App','Cash','Card','App','Cash','Card',
                     'App','Cash','Card','App','Cash','Card','App','Cash'],
    'Branch':['Nasr City','Maadi','Maadi','Nasr City','Heliopolis','Zamalek','Maadi','Zamalek',
              'Nasr City','Heliopolis','Maadi','Zamalek','Nasr City','Heliopolis','Maadi','Zamalek',
              'Nasr City','Heliopolis','Maadi','Zamalek','Nasr City','Heliopolis','Maadi','Zamalek',
              'Nasr City','Heliopolis','Maadi','Zamalek','Nasr City','Heliopolis','Maadi','Zamalek']
})

restaurant_orders.to_csv('restaurant_orders.csv', index=False)
print(restaurant_orders.shape)

(32, 11)

In [37]:
df4 = pd.read_csv('restaurant_orders.csv')
print("First 5 rows:")
print(df4.head())

df4.info()

First 5 rows:
   OrderID   OrderDate    Meal   Category   Channel  Quantity  UnitPrice  \
0      301  2024-03-01  Burger  Fast Food  Delivery         2        8.5
1      302  2024-03-01   Pizza    Italian   Dine-in         1       12.0
2      303  2024-03-02   Pasta    Italian  Delivery         1       10.5
3      304  2024-03-02   Salad    Healthy  Takeaway         2        6.0
4      305  2024-03-03  Burger  Fast Food   Dine-in         3        8.5

   Rating  DeliveryMinutes PaymentMethod      Branch
0     4.6               32           App   Nasr City
1     4.8                0          Card       Maadi
2     4.1               45           App       Maadi
3     4.4                0          Cash   Nasr City
4     4.7                0          Card  Heliopolis
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          32 non-null     int64
 1   OrderDate        32 non-null     object
 2   Meal             32 non-null     object
 3   Category         32 non-null     object
 4   Channel          32 non-null     object
 5   Quantity         32 non-null     int64
 6   UnitPrice        32 non-null     float64
 7   Rating           32 non-null     float64
 8   DeliveryMinutes  32 non-null     int64
 9   PaymentMethod    32 non-null     object
 10  Branch           32 non-null     object
dtypes: float64(2), int64(3), object(6)
memory usage: 2.9+ KB

In [38]:
df4.describe()

          OrderID   Quantity  UnitPrice     Rating  DeliveryMinutes
count   32.000000  32.000000  32.000000  32.000000        32.000000
mean   316.500000   1.687500  10.421875   4.384375        15.250000
std      9.380832   0.737804   3.634755   0.334191        18.878218
min    301.000000   1.000000   4.000000   3.800000         0.000000
25%    308.750000   1.000000   8.500000   4.100000         0.000000
50%    316.500000   2.000000  10.750000   4.400000         0.000000
75%    324.250000   2.000000  12.500000   4.625000        36.000000
max    332.000000   3.000000  16.000000   4.900000        45.000000

In [39]:
df4.loc[0:4, ['Meal','Channel','Rating']]

     Meal   Channel  Rating
0  Burger  Delivery     4.6
1   Pizza   Dine-in     4.8
2   Pasta  Delivery     4.1
3   Salad  Takeaway     4.4
4  Burger   Dine-in     4.7

In [41]:
df4[['Meal','Category','Channel','Quantity','UnitPrice','Rating']]

               Meal   Category   Channel  Quantity  UnitPrice  Rating
0            Burger  Fast Food  Delivery         2        8.5     4.6
1             Pizza    Italian   Dine-in         1       12.0     4.8
2             Pasta    Italian  Delivery         1       10.5     4.1
3             Salad    Healthy  Takeaway         2        6.0     4.4
4            Burger  Fast Food   Dine-in         3        8.5     4.7
5             Sushi      Asian  Delivery         1       16.0     4.9
6             Pizza    Italian  Delivery         2       12.0     4.3
7             Ramen      Asian  Takeaway         1       14.0     4.0
8             Fries  Fast Food   Dine-in         2        4.0     3.9
9   Grilled Chicken    Healthy  Delivery         1       11.0     4.5
10           Burger  Fast Food  Takeaway         2        8.5     4.2
11            Pizza    Italian   Dine-in         1       12.0     4.6
12            Pasta    Italian  Delivery         3       10.5     4.0
13            Salad    Healthy  Takeaway         1        6.0     4.3
14            Sushi      Asian   Dine-in         2       16.0     4.8
15            Ramen      Asian  Delivery         1       14.0     3.9
16            Fries  Fast Food  Takeaway         2        4.0     4.1
17  Grilled Chicken    Healthy   Dine-in         3       11.0     4.4
18           Burger  Fast Food  Delivery         1        8.5     4.5
19            Pizza    Italian  Takeaway         2       12.0     4.7
20            Pasta    Italian   Dine-in         1       10.5     4.2
21            Salad    Healthy  Delivery         2        6.0     4.6
22            Sushi      Asian  Takeaway         1       16.0     4.9
23            Ramen      Asian   Dine-in         3       14.0     4.0
24            Fries  Fast Food  Delivery         1        4.0     3.8
25  Grilled Chicken    Healthy  Takeaway         2       11.0     4.3
26           Burger  Fast Food   Dine-in         1        8.5     4.6
27            Pizza    Italian  Delivery         2       12.0     4.8
28            Pasta    Italian  Takeaway         1       10.5     4.1
29            Salad    Healthy   Dine-in         3        6.0     4.4
30            Sushi      Asian  Delivery         1       16.0     4.9
31            Ramen      Asian  Takeaway         2       14.0     4.0

In [42]:
df4[df4['Channel'] == 'Delivery']

,OrderID,OrderDate,Meal,Category,Channel,Quantity,UnitPrice,Rating,DeliveryMinutes,PaymentMethod,Branch
0,301,2024-03-01,Burger,Fast Food,Delivery,2,8.5,4.6,32,App,Nasr City
2,303,2024-03-02,Pasta,Italian,Delivery,1,10.5,4.1,45,App,Maadi
5,306,2024-03-03,Sushi,Asian,Delivery,1,16.0,4.9,38,App,Zamalek
6,307,2024-03-04,Pizza,Italian,Delivery,2,12.0,4.3,41,App,Maadi
9,310,2024-03-07,Grilled Chicken,Healthy,Delivery,1,11.0,4.5,35,App,Heliopolis
12,313,2024-03-10,Pasta,Italian,Delivery,3,10.5,4.0,40,App,Nasr City
15,316,2024-03-13,Ramen,Asian,Delivery,1,14.0,3.9,0,App,Zamalek
18,319,2024-03-16,Burger,Fast Food,Delivery,1,8.5,4.5,0,App,Maadi
21,322,2024-03-19,Salad,Healthy,Delivery,2,6.0,4.6,0,App,Heliopolis
24,325,2024-03-22,Fries,Fast Food,Delivery,1,4.0,3.8,0,App,Nasr City
27,328,2024-03-25,Pizza,Italian,Delivery,2,12.0,4.8,39,App,Zamalek
30,331,2024-03-28,Sushi,Asian,Delivery,1,16.0,4.9,36,App,Maadi

In [45]:
df4[df4['Rating'] >= 4.5]

,OrderID,OrderDate,Meal,Category,Channel,Quantity,UnitPrice,Rating,DeliveryMinutes,PaymentMethod,Branch
0,301,2024-03-01,Burger,Fast Food,Delivery,2,8.5,4.6,32,App,Nasr City
1,302,2024-03-01,Pizza,Italian,Dine-in,1,12.0,4.8,0,Card,Maadi
4,305,2024-03-03,Burger,Fast Food,Dine-in,3,8.5,4.7,0,Card,Heliopolis
5,306,2024-03-03,Sushi,Asian,Delivery,1,16.0,4.9,38,App,Zamalek
9,310,2024-03-07,Grilled Chicken,Healthy,Delivery,1,11.0,4.5,35,App,Heliopolis
11,312,2024-03-09,Pizza,Italian,Dine-in,1,12.0,4.6,0,Card,Zamalek
14,315,2024-03-12,Sushi,Asian,Dine-in,2,16.0,4.8,36,Card,Maadi
18,319,2024-03-16,Burger,Fast Food,Delivery,1,8.5,4.5,0,App,Maadi
19,320,2024-03-17,Pizza,Italian,Takeaway,2,12.0,4.7,0,Cash,Zamalek
21,322,2024-03-19,Salad,Healthy,Delivery,2,6.0,4.6,0,App,Heliopolis
22,323,2024-03-20,Sushi,Asian,Takeaway,1,16.0,4.9,37,Cash,Maadi
26,327,2024-03-24,Burger,Fast Food,Dine-in,1,8.5,4.6,0,Card,Maadi
27,328,2024-03-25,Pizza,Italian,Delivery,2,12.0,4.8,39,App,Zamalek
30,331,2024-03-28,Sushi,Asian,Delivery,1,16.0,4.9,36,App,Maadi

In [44]:
df4[(df4['Quantity'] >= 2) & (df4['UnitPrice'] > 10)]

,OrderID,OrderDate,Meal,Category,Channel,Quantity,UnitPrice,Rating,DeliveryMinutes,PaymentMethod,Branch
6,307,2024-03-04,Pizza,Italian,Delivery,2,12.0,4.3,41,App,Maadi
12,313,2024-03-10,Pasta,Italian,Delivery,3,10.5,4.0,40,App,Nasr City
14,315,2024-03-12,Sushi,Asian,Dine-in,2,16.0,4.8,36,Card,Maadi
17,318,2024-03-15,Grilled Chicken,Healthy,Dine-in,3,11.0,4.4,33,Card,Heliopolis
19,320,2024-03-17,Pizza,Italian,Takeaway,2,12.0,4.7,0,Cash,Zamalek
23,324,2024-03-21,Ramen,Asian,Dine-in,3,14.0,4.0,0,Card,Zamalek
25,326,2024-03-23,Grilled Chicken,Healthy,Takeaway,2,11.0,4.3,34,Cash,Heliopolis
27,328,2024-03-25,Pizza,Italian,Delivery,2,12.0,4.8,39,App,Zamalek
31,332,2024-03-29,Ramen,Asian,Takeaway,2,14.0,4.0,0,Cash,Zamalek