In [35]:
print("python for data analysis")

python for data analysis

In [36]:
import pandas as pd

df = pd.read_excel('D:/TECHTRECK/Raw_Retail_Sales_Dataset_5000.xlsx', engine='openpyxl')
pd.set_option('display.max_columns', 50)  #to display all columns in the output

In [37]:
print("First 5 rows:")
print(df.head())

First 5 rows:
    Order_ID  Order_Date Order_Time               Branch Sales_Channel  \
0  ORD000001  2025-04-25      21:05               Smouha   TikTok Shop
1  ORD000002  2025-01-07      14:10              Stanley      WhatsApp
2  ORD000003  2025-03-22      15:15               Smouha         Store
3  ORD000004  2025-10-01      12:15                Miami     Instagram
4  ORD000005  2025-08-05      20:50  Downtown Alexandria     Instagram

  Customer_ID Customer_Gender  Customer_Age Customer_Area Product_ID  \
0       C0433            Male            19        Smouha       P001
1       C0105            Male            42        Smouha       P025
2       C0678            Male            36        Smouha       P018
3       C0389          Female            58      Victoria       P023
4       C0147          Female            26       Stanley       P030

           Product_Name            Category      Brand  Unit_Price  Quantity  \
0  Basic Cotton T-Shirt        Men Clothing  UrbanWear      212.22         1
1          Skincare Set  Beauty & Fragrance   BlueLine      783.53         4
2            Sunglasses         Accessories  UrbanWear      500.98         4
3             Body Mist  Beauty & Fragrance  UrbanWear      322.97         3
4        Aroma Diffuser    Home & Lifestyle   TrendHub      678.23         2

   Discount_Percent Payment_Method    Marketing_Source   Campaign_Name  \
0              0.15            COD            Referral     No Campaign
1              0.20       InstaPay            Referral     Winter Sale
2              0.00           Cash            Facebook     Winter Sale
3              0.15       InstaPay  WhatsApp Broadcast    Black Friday
4              0.10       InstaPay       Google Search  Ramadan Offers

  Returned Return_Reason  Rating  Stock_Available_Before_Sale        Supplier  \
0       No           NaN     3.9                          188        In-house
1       No           NaN     4.5                          191        In-house
2       No           NaN     3.6                          218  Imported Batch
3       No           NaN     4.4                           63  Local Supplier
4       No           NaN     3.6                          154        In-house

   Lead_Time_Days  Competitor_Price Weather  Season
0               5            214.83   Rainy  Spring
1              14            729.63     Hot  Winter
2               5            497.25  Cloudy  Spring
3               7            323.06   Sunny  Autumn
4               7            647.59  Cloudy  Summer

In [38]:
df.tail(10)

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
4990,ORD004991,2026-04-21,11:30,Smouha,Website,C0881,Male,41,Sidi Bishr,P024,Hair Serum,Beauty & Fragrance,BlueLine,381.05,1,0.00,Cash,Instagram Ads,Winter Sale,No,NaN,3.5,136,Imported Batch,7,377.45,Sunny,Spring
4991,ORD004992,2025-07-03,14:05,Smouha,Store,C0251,Female,60,Roushdy,P027,Ceramic Mug,Home & Lifestyle,AlexStyle,181.27,2,0.00,Mobile Wallet,WhatsApp Broadcast,Black Friday,No,NaN,2.6,201,Local Supplier,7,191.96,Rainy,Summer
4992,ORD004993,2025-05-07,19:50,Roushdy,WhatsApp,C0693,Male,48,Louran,P005,Hoodie,Men Clothing,AlexStyle,853.78,1,0.05,COD,WhatsApp Broadcast,Summer Sale,No,NaN,3.4,150,Imported Batch,7,847.88,Windy,Spring
4993,ORD004994,2026-03-30,14:05,Stanley,WhatsApp,C0804,Male,41,Sporting,P027,Ceramic Mug,Home & Lifestyle,TrendHub,195.21,1,0.10,COD,WhatsApp Broadcast,Summer Sale,No,NaN,4.0,49,In-house,14,188.78,Sunny,Spring
4994,ORD004995,2026-02-01,17:30,Smouha,TikTok Shop,C0183,Male,52,Sidi Bishr,P021,Men Perfume 50ml,Beauty & Fragrance,BlueLine,640.06,4,0.05,Card,Referral,Black Friday,No,NaN,4.0,154,Cairo Distributor,10,705.66,Hot,Winter
4995,ORD004996,2026-03-23,17:30,Miami,Website,C0033,Male,64,Gleem,P019,Cap,Accessories,UrbanWear,207.34,2,0.00,Cash,Instagram Ads,Black Friday,No,NaN,3.2,115,In-house,10,233.92,Rainy,Spring
4996,ORD004997,2026-05-24,12:15,Miami,Store,C0406,Male,36,Smouha,P007,Basic Blouse,Women Clothing,TrendHub,437.29,2,0.20,InstaPay,Instagram Ads,Summer Sale,No,NaN,4.7,147,Imported Batch,3,457.58,Cloudy,Spring
4997,ORD004998,2025-09-21,13:15,Stanley,Instagram,C0334,Female,35,Smouha,P005,Hoodie,Men Clothing,TrendHub,921.53,4,0.20,Cash,Facebook,Summer Sale,No,NaN,3.0,241,Cairo Distributor,10,838.79,Windy,Autumn
4998,ORD004999,2026-02-02,10:50,Miami,TikTok Shop,C0778,Male,34,Miami,P018,Sunglasses,Accessories,TrendHub,516.24,2,0.10,COD,Google Search,No Campaign,No,NaN,4.7,210,In-house,5,558.30,Windy,Winter
4999,ORD005000,2026-03-06,22:15,Miami,WhatsApp,C0121,Male,28,Louran,P016,Leather Belt,Accessories,TrendHub,382.34,3,0.05,Card,Instagram Ads,Black Friday,No,NaN,2.7,118,Imported Batch,5,348.32,Hot,Spring

In [39]:
print("Random 5 rows:")
df.sample(5, random_state=42) # Displaying random rows

Random 5 rows:

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
1501,ORD001502,2025-08-16,22:30,Mandara,Website,C0351,Female,29,Stanley,P009,Casual Dress,Women Clothing,UrbanWear,963.56,4,0.15,Mobile Wallet,Facebook,Back to School,No,NaN,4.3,14,Local Supplier,7,946.84,Rainy,Summer
2586,ORD002587,2025-10-25,12:45,Downtown Alexandria,Website,C0089,Female,37,Stanley,P018,Sunglasses,Accessories,AlexStyle,470.51,2,0.20,COD,Walk-in,Summer Sale,No,NaN,4.1,172,Imported Batch,14,437.28,Sunny,Autumn
2653,ORD002654,2025-07-03,12:00,Stanley,TikTok Shop,C0736,Female,42,Sidi Bishr,P005,Hoodie,Men Clothing,TrendHub,804.31,2,0.00,COD,Walk-in,Winter Sale,No,NaN,3.6,23,In-house,3,891.94,Sunny,Summer
1055,ORD001056,2025-11-02,16:45,Mandara,Instagram,C0662,Female,28,Sporting,P025,Skincare Set,Beauty & Fragrance,UrbanWear,726.88,2,0.10,InstaPay,TikTok,Summer Sale,No,NaN,4.0,72,Imported Batch,3,736.45,Sunny,Autumn
705,ORD000706,2025-12-17,20:20,Roushdy,WhatsApp,C0609,Male,38,Gleem,P018,Sunglasses,Accessories,UrbanWear,447.64,2,0.10,Card,TikTok,Winter Sale,No,NaN,3.0,90,In-house,7,432.41,Hot,Winter

In [40]:
df.sample(5)

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
2346,ORD002347,2025-03-04,11:15,Sidi Bishr,Store,C0119,Male,31,Smouha,P007,Basic Blouse,Women Clothing,BlueLine,400.21,2,0.00,InstaPay,WhatsApp Broadcast,Winter Sale,No,NaN,3.0,77,Cairo Distributor,10,424.44,Windy,Spring
218,ORD000219,2026-04-14,10:00,Stanley,Instagram,C0595,Male,38,Gleem,P004,Polo Shirt,Men Clothing,TrendHub,422.75,4,0.15,InstaPay,Instagram Ads,Ramadan Offers,No,NaN,3.2,73,In-house,14,416.74,Cloudy,Spring
239,ORD000240,2026-01-04,14:00,Miami,WhatsApp,C0007,Female,32,Stanley,P015,Slides,Footwear,BlueLine,447.41,1,0.05,InstaPay,Referral,Ramadan Offers,Yes,Wrong Size,3.9,242,Cairo Distributor,3,406.89,Rainy,Winter
4140,ORD004141,2026-06-04,18:10,Smouha,Store,C0560,Male,37,Victoria,P007,Basic Blouse,Women Clothing,BlueLine,458.03,1,0.20,Mobile Wallet,Walk-in,Black Friday,No,NaN,3.9,153,In-house,5,441.24,Rainy,Summer
1847,ORD001848,2025-03-15,12:00,Stanley,Store,C0160,Female,38,Sporting,P019,Cap,Accessories,BlueLine,226.72,1,0.00,InstaPay,Referral,Ramadan Offers,Yes,Other,4.4,52,Cairo Distributor,3,215.91,Sunny,Spring

In [41]:
df.shape
row , col = df.shape
print(row , col)

5000 28

In [42]:
df.columns
## to convert to normal list
list(df.columns)

['Order_ID',
 'Order_Date',
 'Order_Time',
 'Branch',
 'Sales_Channel',
 'Customer_ID',
 'Customer_Gender',
 'Customer_Age',
 'Customer_Area',
 'Product_ID',
 'Product_Name',
 'Category',
 'Brand',
 'Unit_Price',
 'Quantity',
 'Discount_Percent',
 'Payment_Method',
 'Marketing_Source',
 'Campaign_Name',
 'Returned',
 'Return_Reason',
 'Rating',
 'Stock_Available_Before_Sale',
 'Supplier',
 'Lead_Time_Days',
 'Competitor_Price',
 'Weather',
 'Season']

In [43]:
print(df.index) ##where start and end
print(df.index.min())  ## the first
print(df.index.max())  ## the last

RangeIndex(start=0, stop=5000, step=1)
0
4999

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order_ID                     5000 non-null   object
 1   Order_Date                   5000 non-null   object
 2   Order_Time                   5000 non-null   object
 3   Branch                       5000 non-null   object
 4   Sales_Channel                5000 non-null   object
 5   Customer_ID                  5000 non-null   object
 6   Customer_Gender              5000 non-null   object
 7   Customer_Age                 5000 non-null   int64
 8   Customer_Area                5000 non-null   object
 9   Product_ID                   5000 non-null   object
 10  Product_Name                 5000 non-null   object
 11  Category                     5000 non-null   object
 12  Brand                        5000 non-null   object
 13  Unit_Price                   5000 non-null   float64
 14  Quantity                     5000 non-null   int64
 15  Discount_Percent             5000 non-null   float64
 16  Payment_Method               5000 non-null   object
 17  Marketing_Source             5000 non-null   object
 18  Campaign_Name                5000 non-null   object
 19  Returned                     5000 non-null   object
 20  Return_Reason                318 non-null    object
 21  Rating                       5000 non-null   float64
 22  Stock_Available_Before_Sale  5000 non-null   int64
 23  Supplier                     5000 non-null   object
 24  Lead_Time_Days               5000 non-null   int64
 25  Competitor_Price             5000 non-null   float64
 26  Weather                      5000 non-null   object
 27  Season                       5000 non-null   object
dtypes: float64(4), int64(4), object(20)
memory usage: 1.1+ MB

In [45]:
print(df.dtypes)
print("----------------------------------------")
print(df.dtypes.value_counts())

Order_ID                        object
Order_Date                      object
Order_Time                      object
Branch                          object
Sales_Channel                   object
Customer_ID                     object
Customer_Gender                 object
Customer_Age                     int64
Customer_Area                   object
Product_ID                      object
Product_Name                    object
Category                        object
Brand                           object
Unit_Price                     float64
Quantity                         int64
Discount_Percent               float64
Payment_Method                  object
Marketing_Source                object
Campaign_Name                   object
Returned                        object
Return_Reason                   object
Rating                         float64
Stock_Available_Before_Sale      int64
Supplier                        object
Lead_Time_Days                   int64
Competitor_Price               float64
Weather                         object
Season                          object
dtype: object
----------------------------------------
object     20
int64       4
float64     4
Name: count, dtype: int64




# Data frame :  عباره عن جدول r +c  من داتا هتدهالو
# students = ({"id":[24030099 , 24030100 , 24030101]
#             ,"names" : ["ziad salah" , "ziad radwan" , "ziad mohamed"]
#             ,"gpa" : [3.59 , 3.3 , 3.48]})

# st = pd.DataFrame(students)
# print(st)            


# # series : عمود واحد
#degree = [ 100 , 102 , 103]
#names = ["ziad" , "ahmed" , "medo"]
#dts = pd.Series(degree , index = names)
#print(dts)

#search :
#print(dts[dts == 100])


#read csv files :
#df = pd.read_csv("C:/Users/Zoz/Desktop/myfile.csv")

In [46]:
students = ({"id":[24030099 , 24030100 , 24030101]
            ,"names" : ["ziad salah" , "ziad radwan" , "ziad mohamed"]
            ,"gpa" : [3.59 , 3.3 , 3.48]})

st = pd.DataFrame(students)
print(st)

         id         names   gpa
0  24030099    ziad salah  3.59
1  24030100   ziad radwan  3.30
2  24030101  ziad mohamed  3.48

In [47]:
df.describe()

,Customer_Age,Unit_Price,Quantity,Discount_Percent,Rating,Stock_Available_Before_Sale,Lead_Time_Days,Competitor_Price
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,41.32860,655.597086,1.985400,0.071330,3.752440,128.608400,7.788600,671.709736
std,13.76791,413.307520,1.064995,0.074858,0.724557,70.878379,3.843913,427.256737
min,18.00000,110.400000,1.000000,0.000000,2.500000,5.000000,3.000000,103.210000
25%,29.00000,317.082500,1.000000,0.000000,3.100000,68.000000,5.000000,326.137500
50%,41.00000,647.680000,2.000000,0.050000,3.800000,130.000000,7.000000,618.855000
75%,53.00000,844.812500,3.000000,0.150000,4.400000,189.000000,10.000000,870.770000
max,65.00000,1877.060000,4.000000,0.200000,5.000000,250.000000,14.000000,2084.350000

In [48]:
df['Product_Name']

0       Basic Cotton T-Shirt
1               Skincare Set
2                 Sunglasses
3                  Body Mist
4             Aroma Diffuser
                ...
4995                     Cap
4996            Basic Blouse
4997                  Hoodie
4998              Sunglasses
4999            Leather Belt
Name: Product_Name, Length: 5000, dtype: object

In [49]:

print(df['Product_Name'].value_counts())

Product_Name
Polo Shirt              193
Basic Blouse            186
Scented Candle          182
Wide Leg Pants          179
Aroma Diffuser          178
Backpack                178
White Sneakers          176
Skincare Set            175
Casual Dress            174
Summer Dress            173
Minimal Wallet          173
Linen Set               173
Hair Serum              172
Slides                  169
Men Perfume 50ml        168
Slim Fit Jeans          168
Notebook                165
Water Bottle            164
Leather Belt            162
Hoodie                  161
Leather Loafers         161
Basic Cotton T-Shirt    159
Running Shoes           158
Cap                     157
Women Perfume 50ml      155
Women Sandals           153
Sunglasses              152
Ceramic Mug             148
Oversized T-Shirt       146
Body Mist               142
Name: count, dtype: int64

In [50]:
print(df['Customer_Area'].unique())
print(df['Customer_Area'].nunique())

['Smouha' 'Victoria' 'Stanley' 'Mandara' 'Sporting' 'Roushdy' 'Louran'
 'Sidi Bishr' 'Gleem' 'Miami']
10

In [51]:
print(df['Branch'].unique())

['Smouha' 'Stanley' 'Miami' 'Downtown Alexandria' 'Sidi Bishr' 'Mandara'
 'Gleem' 'Roushdy']

In [52]:
print(df['Customer_Gender'].unique())

['Male' 'Female']

In [53]:
df.isnull().sum()

Order_ID                          0
Order_Date                        0
Order_Time                        0
Branch                            0
Sales_Channel                     0
Customer_ID                       0
Customer_Gender                   0
Customer_Age                      0
Customer_Area                     0
Product_ID                        0
Product_Name                      0
Category                          0
Brand                             0
Unit_Price                        0
Quantity                          0
Discount_Percent                  0
Payment_Method                    0
Marketing_Source                  0
Campaign_Name                     0
Returned                          0
Return_Reason                  4682
Rating                            0
Stock_Available_Before_Sale       0
Supplier                          0
Lead_Time_Days                    0
Competitor_Price                  0
Weather                           0
Season                            0
dtype: int64

In [54]:
print(df['Quantity'].isnull().mean())

0.0

In [55]:
print(df.isnull().sum())

missing_values = df['Return_Reason'].isnull().sum()
print(f"missing values in Return_Reason: {missing_values}")


print('----------------------------------')

print(df['Order_Time'].sort_values())

Order_ID                          0
Order_Date                        0
Order_Time                        0
Branch                            0
Sales_Channel                     0
Customer_ID                       0
Customer_Gender                   0
Customer_Age                      0
Customer_Area                     0
Product_ID                        0
Product_Name                      0
Category                          0
Brand                             0
Unit_Price                        0
Quantity                          0
Discount_Percent                  0
Payment_Method                    0
Marketing_Source                  0
Campaign_Name                     0
Returned                          0
Return_Reason                  4682
Rating                            0
Stock_Available_Before_Sale       0
Supplier                          0
Lead_Time_Days                    0
Competitor_Price                  0
Weather                           0
Season                            0
dtype: int64
missing values in Return_Reason: 4682
----------------------------------
2290    10:00
2159    10:00
2300    10:00
4722    10:00
4454    10:00
        ...
2444    22:50
1860    22:50
3843    22:50
2475    22:50
3207    22:50
Name: Order_Time, Length: 5000, dtype: object

In [56]:
print(df.duplicated().sum())

0

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order_ID                     5000 non-null   object
 1   Order_Date                   5000 non-null   object
 2   Order_Time                   5000 non-null   object
 3   Branch                       5000 non-null   object
 4   Sales_Channel                5000 non-null   object
 5   Customer_ID                  5000 non-null   object
 6   Customer_Gender              5000 non-null   object
 7   Customer_Age                 5000 non-null   int64
 8   Customer_Area                5000 non-null   object
 9   Product_ID                   5000 non-null   object
 10  Product_Name                 5000 non-null   object
 11  Category                     5000 non-null   object
 12  Brand                        5000 non-null   object
 13  Unit_Price                   5000 non-null   float64
 14  Quantity                     5000 non-null   int64
 15  Discount_Percent             5000 non-null   float64
 16  Payment_Method               5000 non-null   object
 17  Marketing_Source             5000 non-null   object
 18  Campaign_Name                5000 non-null   object
 19  Returned                     5000 non-null   object
 20  Return_Reason                318 non-null    object
 21  Rating                       5000 non-null   float64
 22  Stock_Available_Before_Sale  5000 non-null   int64
 23  Supplier                     5000 non-null   object
 24  Lead_Time_Days               5000 non-null   int64
 25  Competitor_Price             5000 non-null   float64
 26  Weather                      5000 non-null   object
 27  Season                       5000 non-null   object
dtypes: float64(4), int64(4), object(20)
memory usage: 1.1+ MB

In [58]:
## filteeer
df[(df["Unit_Price"] > 500) & (df["Discount_Percent"] == 0.20)]

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
1,ORD000002,2025-01-07,14:10,Stanley,WhatsApp,C0105,Male,42,Smouha,P025,Skincare Set,Beauty & Fragrance,BlueLine,783.53,4,0.2,InstaPay,Referral,Winter Sale,No,NaN,4.5,191,In-house,14,729.63,Hot,Winter
25,ORD000026,2025-12-27,16:15,Mandara,Website,C0280,Female,49,Sidi Bishr,P010,Linen Set,Women Clothing,NovaFashion,1296.03,1,0.2,Mobile Wallet,Google Search,Summer Sale,No,NaN,4.6,240,Cairo Distributor,14,1339.49,Hot,Winter
28,ORD000029,2025-04-28,19:00,Roushdy,TikTok Shop,C0694,Female,43,Stanley,P025,Skincare Set,Beauty & Fragrance,AlexStyle,766.12,2,0.2,Card,Walk-in,Back to School,No,NaN,4.4,222,Local Supplier,14,839.41,Rainy,Spring
30,ORD000031,2025-10-02,14:50,Stanley,Instagram,C0584,Female,39,Sidi Bishr,P011,White Sneakers,Footwear,NovaFashion,1605.04,4,0.2,InstaPay,Instagram Ads,Weekend Promo,No,NaN,3.0,209,Imported Batch,7,1556.75,Windy,Autumn
42,ORD000043,2025-12-15,14:20,Mandara,Website,C0458,Female,40,Gleem,P030,Aroma Diffuser,Home & Lifestyle,TrendHub,748.04,4,0.2,COD,Facebook,Weekend Promo,No,NaN,4.8,227,Cairo Distributor,5,780.17,Cloudy,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4909,ORD004910,2025-10-18,15:50,Sidi Bishr,Website,C0868,Male,36,Gleem,P022,Women Perfume 50ml,Beauty & Fragrance,TrendHub,724.29,1,0.2,Card,Facebook,Weekend Promo,No,NaN,4.4,213,Cairo Distributor,3,769.44,Windy,Autumn
4924,ORD004925,2025-11-26,22:20,Miami,TikTok Shop,C0080,Male,55,Stanley,P014,Women Sandals,Footwear,AlexStyle,807.99,1,0.2,Card,Walk-in,No Campaign,No,NaN,4.2,64,Local Supplier,3,927.04,Sunny,Autumn
4963,ORD004964,2025-03-20,10:45,Sidi Bishr,Website,C0715,Male,22,Gleem,P009,Casual Dress,Women Clothing,TrendHub,900.68,1,0.2,Card,Google Search,Ramadan Offers,No,NaN,4.5,18,Imported Batch,10,1026.24,Windy,Spring
4976,ORD004977,2025-01-14,16:05,Stanley,TikTok Shop,C0836,Female,33,Roushdy,P030,Aroma Diffuser,Home & Lifestyle,UrbanWear,716.17,1,0.2,Mobile Wallet,WhatsApp Broadcast,No Campaign,No,NaN,4.2,207,Local Supplier,5,778.66,Cloudy,Winter
4997,ORD004998,2025-09-21,13:15,Stanley,Instagram,C0334,Female,35,Smouha,P005,Hoodie,Men Clothing,TrendHub,921.53,4,0.2,Cash,Facebook,Summer Sale,No,NaN,3.0,241,Cairo Distributor,10,838.79,Windy,Autumn

In [59]:
dc = pd.read_csv('D:/TECHTRECK/retail_sales_raw.csv')

print(dc.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2628 entries, 0 to 2627
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order ID         2628 non-null   object
 1   Order Date       2628 non-null   object
 2   Customer ID      2628 non-null   object
 3   Product ID       2628 non-null   object
 4   Category         2628 non-null   object
 5   Product          2628 non-null   object
 6   Region           2628 non-null   object
 7   City             2589 non-null   object
 8   Channel          2628 non-null   object
 9   Payment Method   2563 non-null   object
 10  Sales Rep        2628 non-null   object
 11  Quantity         2628 non-null   int64
 12  Unit Price       2612 non-null   float64
 13  Unit Cost        2628 non-null   float64
 14  Discount %       2628 non-null   float64
 15  Shipping Cost    2628 non-null   float64
 16  Customer Rating  2419 non-null   float64
 17  Returned         2628 non-null   object
dtypes: float64(5), int64(1), object(12)
memory usage: 369.7+ KB
None

In [60]:
dc.describe()

,Quantity,Unit Price,Unit Cost,Discount %,Shipping Cost,Customer Rating
count,2628.000000,2612.000000,2628.000000,2628.000000,2628.000000,2419.000000
mean,1.811263,5553.607343,3736.032922,4.726027,108.324041,4.111823
std,1.590367,8036.763066,6184.797414,6.869071,53.930365,0.592440
min,1.000000,585.730000,235.890000,0.000000,35.010000,2.100000
25%,1.000000,1320.670000,614.462500,0.000000,74.977500,3.700000
50%,1.000000,2404.015000,1246.920000,0.000000,106.735000,4.100000
75%,2.000000,4286.987500,2641.202500,10.000000,137.885000,4.500000
max,29.000000,35795.690000,28928.560000,25.000000,1087.440000,5.000000

In [61]:
list(dc.columns)

['Order ID',
 'Order Date',
 'Customer ID',
 'Product ID',
 'Category',
 'Product',
 'Region',
 'City',
 'Channel',
 'Payment Method',
 'Sales Rep',
 'Quantity',
 'Unit Price',
 'Unit Cost',
 'Discount %',
 'Shipping Cost',
 'Customer Rating',
 'Returned']

In [62]:
print(dc.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2628 entries, 0 to 2627
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order ID         2628 non-null   object
 1   Order Date       2628 non-null   object
 2   Customer ID      2628 non-null   object
 3   Product ID       2628 non-null   object
 4   Category         2628 non-null   object
 5   Product          2628 non-null   object
 6   Region           2628 non-null   object
 7   City             2589 non-null   object
 8   Channel          2628 non-null   object
 9   Payment Method   2563 non-null   object
 10  Sales Rep        2628 non-null   object
 11  Quantity         2628 non-null   int64
 12  Unit Price       2612 non-null   float64
 13  Unit Cost        2628 non-null   float64
 14  Discount %       2628 non-null   float64
 15  Shipping Cost    2628 non-null   float64
 16  Customer Rating  2419 non-null   float64
 17  Returned         2628 non-null   object
dtypes: float64(5), int64(1), object(12)
memory usage: 369.7+ KB
None

In [63]:
print(dc.shape)
row , col = dc.shape
print(row , col)

(2628, 18)
2628 18

In [64]:
dc.columns
## to convert to normal list
list(dc.columns)

['Order ID',
 'Order Date',
 'Customer ID',
 'Product ID',
 'Category',
 'Product',
 'Region',
 'City',
 'Channel',
 'Payment Method',
 'Sales Rep',
 'Quantity',
 'Unit Price',
 'Unit Cost',
 'Discount %',
 'Shipping Cost',
 'Customer Rating',
 'Returned']

In [65]:
print(dc.dtypes)
print("----------------------------------------")
print(dc.dtypes.value_counts())

Order ID            object
Order Date          object
Customer ID         object
Product ID          object
Category            object
Product             object
Region              object
City                object
Channel             object
Payment Method      object
Sales Rep           object
Quantity             int64
Unit Price         float64
Unit Cost          float64
Discount %         float64
Shipping Cost      float64
Customer Rating    float64
Returned            object
dtype: object
----------------------------------------
object     12
float64     5
int64       1
Name: count, dtype: int64

In [66]:
print(dc.index) ##where start and end
print(dc.index.min())  ## the first
print(dc.index.max())  ## the last

RangeIndex(start=0, stop=2628, step=1)
0
2627

In [67]:
print("First 5 rows:")
print(dc.head())

print("Random 5 rows:")
print(dc.sample(5, random_state=42))  # Displaying random rows

First 5 rows:
     Order ID  Order Date Customer ID Product ID        Category  \
0  ORD-100232  2025-09-08       C0370       P016          Beauty
1  ORD-102198  2025-08-22       C0090       P016          Beauty
2  ORD-100331  2025-01-20       C0305       P013          Beauty
3  ORD-100920  2025-04-26       C0256       P008  Home & Kitchen
4  ORD-102003  2025-08-18       C0674       P015          Beauty

        Product      Region        City      Channel    Payment Method  \
0    Makeup Kit       Delta    Mansoura  Marketplace  Cash on Delivery
1    Makeup Kit       Delta       Tanta        Store       Credit Card
2       Perfume       Cairo   New Cairo   Mobile App       Credit Card
3  Cookware Set  Alexandria  Sidi Gaber      Website       Credit Card
4    Hair Dryer  Alexandria  Sidi Gaber   Mobile App       Credit Card

  Sales Rep  Quantity  Unit Price  Unit Cost  Discount %  Shipping Cost  \
0      Nour         1     1216.26     491.81        10.0          44.39
1     Ahmed         1     1083.75     446.99         5.0         150.17
2      Mona         1     1714.56     768.15         0.0          90.13
3      Mona         2     2652.80    1390.62        20.0          45.20
4     Laila         1     1336.18     643.23         0.0          63.88

   Customer Rating Returned
0              3.4      Yes
1              3.9       No
2              NaN       No
3              3.8       No
4              NaN       No
Random 5 rows:
        Order ID  Order Date Customer ID Product ID        Category  \
221   ORD-100504  2025-07-28       C0556       P019          Sports
318   ORD-100069  2025-08-11       C0660       P017          Sports
926   ORD-102013  2025-12-14       C0281       P011         Fashion
2488  ORD-102065  2025-12-06       C0515       P008  Home & Kitchen
1420  ORD-102185  2025-07-13       C0347       P005  Home & Kitchen

           Product      Region        City      Channel    Payment Method  \
221       Football       Cairo       Maadi        Store  Cash on Delivery
318   Dumbbell Set  Alexandria       Miami   Mobile App  Cash on Delivery
926       Backpack       Cairo   Nasr City      Website  Cash on Delivery
2488  Cookware Set       Cairo   Nasr City  Marketplace  Cash on Delivery
1420       Blender       Cairo  Heliopolis  Marketplace       Credit Card

     Sales Rep  Quantity  Unit Price  Unit Cost  Discount %  Shipping Cost  \
221       Mona         2      930.83     406.75         0.0          54.31
318      Ahmed         1     2665.32    1551.61         5.0         105.87
926      Ahmed         1     1502.22     667.80         0.0         105.03
2488      Mona         1     2608.00    1461.20         0.0          46.77
1420    Khaled         1     2234.39    1361.02        10.0         148.39

      Customer Rating Returned
221               4.0       No
318               4.1      Yes
926               4.1       No
2488              4.3       No
1420              4.0       No

In [68]:
print(dc[['Order ID', 'Order Date']])

        Order ID  Order Date
0     ORD-100232  2025-09-08
1     ORD-102198  2025-08-22
2     ORD-100331  2025-01-20
3     ORD-100920  2025-04-26
4     ORD-102003  2025-08-18
...          ...         ...
2623  ORD-101697  2025-07-15
2624  ORD-100332  2025-12-28
2625  ORD-101293  2025-10-20
2626  ORD-101104  2025-10-13
2627  ORD-101945  2025-06-04

[2628 rows x 2 columns]

In [69]:
print(dc['City'].value_counts())

City
Damietta      187
Tanta         179
Nasr City     179
Minya         177
Agami         169
Miami         168
Mansoura      168
Zagazig       163
New Cairo     160
Assiut        158
Luxor         158
Heliopolis    154
Maadi         153
Sidi Gaber    149
Smouha        138
Sohag         129
Name: count, dtype: int64

In [70]:
print(dc['Region'].unique())
print(dc['Region'].nunique())

['Delta' 'Cairo' 'Alexandria' 'Upper Egypt']
4

In [71]:
print(dc.isnull().sum())

Order ID             0
Order Date           0
Customer ID          0
Product ID           0
Category             0
Product              0
Region               0
City                39
Channel              0
Payment Method      65
Sales Rep            0
Quantity             0
Unit Price          16
Unit Cost            0
Discount %           0
Shipping Cost        0
Customer Rating    209
Returned             0
dtype: int64

In [72]:
dc.tail()

,Order ID,Order Date,Customer ID,Product ID,Category,Product,Region,City,Channel,Payment Method,Sales Rep,Quantity,Unit Price,Unit Cost,Discount %,Shipping Cost,Customer Rating,Returned
2623,ORD-101697,2025-07-15,C0208,P012,Fashion,T-Shirt,Cairo,Nasr City,Marketplace,Wallet,Sara,1,671.71,266.44,0.0,72.57,NaN,No
2624,ORD-100332,2025-12-28,C0503,P003,Electronics,Headphones,Alexandria,Smouha,Website,Cash on Delivery,Youssef,5,2007.93,1094.17,0.0,75.45,3.2,No
2625,ORD-101293,2025-10-20,C0692,P008,Home & Kitchen,Cookware Set,Delta,Damietta,Mobile App,Wallet,Nour,1,2860.95,1517.97,10.0,122.75,4.6,No
2626,ORD-101104,2025-10-13,C0234,P003,Electronics,Headphones,Alexandria,Agami,Store,Credit Card,Omar,1,1866.62,1075.05,0.0,112.49,4.5,No
2627,ORD-101945,2025-06-04,C0428,P011,Fashion,Backpack,Alexandria,Miami,Mobile App,Cash on Delivery,Sara,3,1389.23,611.77,10.0,37.53,4.4,No

In [73]:
missing_values = dc['Shipping Cost'].isnull().sum()
print(f"missing values in Shipping Cost: {missing_values}")

missing values in Shipping Cost: 0

In [74]:
print(dc['Shipping Cost'].sort_values())

137       35.01
310       35.02
1212      35.16
2467      35.18
808       35.19
         ...
2007     768.32
2039     783.68
1629     783.68
1552     833.84
1818    1087.44
Name: Shipping Cost, Length: 2628, dtype: float64

In [76]:
print(dc['Payment Method'].duplicated().sum())
print(dc['Payment Method'].duplicated())

2623
0       False
1       False
2        True
3        True
4        True
        ...
2623     True
2624     True
2625     True
2626     True
2627     True
Name: Payment Method, Length: 2628, dtype: bool

In [77]:
df.describe(include='all')

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
count,5000,5000,5000,5000,5000,5000,5000,5000.00000,5000,5000,5000,5000,5000,5000.000000,5000.000000,5000.000000,5000,5000,5000,5000,318,5000.000000,5000.000000,5000,5000.000000,5000.000000,5000,5000
unique,5000,542,104,8,5,897,2,NaN,10,30,30,6,5,NaN,NaN,NaN,5,7,7,2,5,NaN,NaN,4,NaN,NaN,5,4
top,ORD005000,2025-06-24,21:45,Smouha,TikTok Shop,C0776,Male,NaN,Roushdy,P004,Polo Shirt,Women Clothing,NovaFashion,NaN,NaN,NaN,COD,Walk-in,Summer Sale,No,Late Delivery,NaN,NaN,In-house,NaN,NaN,Cloudy,Spring
freq,1,20,63,671,1028,14,2554,NaN,535,193,193,885,1053,NaN,NaN,NaN,1011,731,769,4682,81,NaN,NaN,1301,NaN,NaN,1015,1743
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.32860,NaN,NaN,NaN,NaN,NaN,655.597086,1.985400,0.071330,NaN,NaN,NaN,NaN,NaN,3.752440,128.608400,NaN,7.788600,671.709736,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.76791,NaN,NaN,NaN,NaN,NaN,413.307520,1.064995,0.074858,NaN,NaN,NaN,NaN,NaN,0.724557,70.878379,NaN,3.843913,427.256737,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.00000,NaN,NaN,NaN,NaN,NaN,110.400000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,2.500000,5.000000,NaN,3.000000,103.210000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.00000,NaN,NaN,NaN,NaN,NaN,317.082500,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,3.100000,68.000000,NaN,5.000000,326.137500,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.00000,NaN,NaN,NaN,NaN,NaN,647.680000,2.000000,0.050000,NaN,NaN,NaN,NaN,NaN,3.800000,130.000000,NaN,7.000000,618.855000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.00000,NaN,NaN,NaN,NaN,NaN,844.812500,3.000000,0.150000,NaN,NaN,NaN,NaN,NaN,4.400000,189.000000,NaN,10.000000,870.770000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.00000,NaN,NaN,NaN,NaN,NaN,1877.060000,4.000000,0.200000,NaN,NaN,NaN,NaN,NaN,5.000000,250.000000,NaN,14.000000,2084.350000,NaN,NaN

In [79]:
dc.select_dtypes(include='number').columns

Index(['Quantity', 'Unit Price', 'Unit Cost', 'Discount %', 'Shipping Cost',
       'Customer Rating'],
      dtype='object')

In [80]:
print(dc['Product'].value_counts())

Product
Treadmill        155
Air Fryer        149
Perfume          148
Headphones       147
Sneakers         143
Makeup Kit       139
Dumbbell Set     134
Smart Watch      134
Coffee Maker     131
Hair Dryer       131
Laptop           128
Skin Care Set    127
T-Shirt          126
Backpack         125
Smartphone       123
Blender          122
Jacket           121
Football         120
Yoga Mat         118
Cookware Set     107
Name: count, dtype: int64

In [81]:
print(dc['Category'].unique())

['Beauty' 'Home & Kitchen' 'Sports' 'fashion' 'Electronics' 'Fashion'
 ' Beauty ' 'sports' 'beauty' 'home & kitchen' ' home & kitchen '
 ' Sports ' 'electronics' ' Electronics ' ' Fashion ' ' Home & Kitchen ']

In [82]:
dc.iloc[0]

Order ID                 ORD-100232
Order Date               2025-09-08
Customer ID                   C0370
Product ID                     P016
Category                     Beauty
Product                  Makeup Kit
Region                        Delta
City                       Mansoura
Channel                 Marketplace
Payment Method     Cash on Delivery
Sales Rep                      Nour
Quantity                          1
Unit Price                  1216.26
Unit Cost                    491.81
Discount %                     10.0
Shipping Cost                 44.39
Customer Rating                 3.4
Returned                        Yes
Name: 0, dtype: object

In [84]:
df.iloc[:3]

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
0,ORD000001,2025-04-25,21:05,Smouha,TikTok Shop,C0433,Male,19,Smouha,P001,Basic Cotton T-Shirt,Men Clothing,UrbanWear,212.22,1,0.15,COD,Referral,No Campaign,No,NaN,3.9,188,In-house,5,214.83,Rainy,Spring
1,ORD000002,2025-01-07,14:10,Stanley,WhatsApp,C0105,Male,42,Smouha,P025,Skincare Set,Beauty & Fragrance,BlueLine,783.53,4,0.20,InstaPay,Referral,Winter Sale,No,NaN,4.5,191,In-house,14,729.63,Hot,Winter
2,ORD000003,2025-03-22,15:15,Smouha,Store,C0678,Male,36,Smouha,P018,Sunglasses,Accessories,UrbanWear,500.98,4,0.00,Cash,Facebook,Winter Sale,No,NaN,3.6,218,Imported Batch,5,497.25,Cloudy,Spring

In [87]:
df.loc[df['Quantity'] > 2]  ## useful for filtering then update the values in the filtered rows

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,Product_Name,Category,Brand,Unit_Price,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
1,ORD000002,2025-01-07,14:10,Stanley,WhatsApp,C0105,Male,42,Smouha,P025,Skincare Set,Beauty & Fragrance,BlueLine,783.53,4,0.20,InstaPay,Referral,Winter Sale,No,NaN,4.5,191,In-house,14,729.63,Hot,Winter
2,ORD000003,2025-03-22,15:15,Smouha,Store,C0678,Male,36,Smouha,P018,Sunglasses,Accessories,UrbanWear,500.98,4,0.00,Cash,Facebook,Winter Sale,No,NaN,3.6,218,Imported Batch,5,497.25,Cloudy,Spring
3,ORD000004,2025-10-01,12:15,Miami,Instagram,C0389,Female,58,Victoria,P023,Body Mist,Beauty & Fragrance,UrbanWear,322.97,3,0.15,InstaPay,WhatsApp Broadcast,Black Friday,No,NaN,4.4,63,Local Supplier,7,323.06,Sunny,Autumn
7,ORD000008,2025-04-25,14:15,Sidi Bishr,Website,C0900,Male,23,Sporting,P030,Aroma Diffuser,Home & Lifestyle,AlexStyle,749.57,4,0.00,COD,WhatsApp Broadcast,Summer Sale,No,NaN,2.8,126,Cairo Distributor,7,773.50,Windy,Spring
11,ORD000012,2026-03-30,20:00,Smouha,Website,C0171,Female,49,Sporting,P026,Scented Candle,Home & Lifestyle,UrbanWear,244.29,4,0.20,Mobile Wallet,Walk-in,Summer Sale,No,NaN,3.4,104,Imported Batch,10,237.28,Windy,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4980,ORD004981,2026-03-20,11:20,Downtown Alexandria,TikTok Shop,C0365,Female,25,Roushdy,P019,Cap,Accessories,UrbanWear,219.55,3,0.20,Mobile Wallet,WhatsApp Broadcast,Weekend Promo,No,NaN,4.1,167,Local Supplier,7,210.19,Windy,Spring
4989,ORD004990,2025-03-11,10:00,Smouha,Website,C0791,Male,41,Stanley,P017,Minimal Wallet,Accessories,AlexStyle,312.50,4,0.10,Cash,Instagram Ads,Black Friday,No,NaN,4.0,17,Imported Batch,10,351.15,Cloudy,Spring
4994,ORD004995,2026-02-01,17:30,Smouha,TikTok Shop,C0183,Male,52,Sidi Bishr,P021,Men Perfume 50ml,Beauty & Fragrance,BlueLine,640.06,4,0.05,Card,Referral,Black Friday,No,NaN,4.0,154,Cairo Distributor,10,705.66,Hot,Winter
4997,ORD004998,2025-09-21,13:15,Stanley,Instagram,C0334,Female,35,Smouha,P005,Hoodie,Men Clothing,TrendHub,921.53,4,0.20,Cash,Facebook,Summer Sale,No,NaN,3.0,241,Cairo Distributor,10,838.79,Windy,Autumn
4999,ORD005000,2026-03-06,22:15,Miami,WhatsApp,C0121,Male,28,Louran,P016,Leather Belt,Accessories,TrendHub,382.34,3,0.05,Card,Instagram Ads,Black Friday,No,NaN,2.7,118,Imported Batch,5,348.32,Hot,Spring