In [30]:
import numpy as np
import pandas as pd
import plotly.express as px

In [31]:
df = pd.read_excel('D:\TECHTRECK\Biased_Raw_Retail_Returns_Dataset_7000.xlsx', engine='openpyxl')

In [114]:
pd.set_option('display.max_columns', 50)  #to display all columns in the output

In [33]:
df.head()

,Order_ID,Order_Date,Order_Time,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Branch,Sales_Channel,Product_Domain,Category,Product_ID,Product_Name,Brand,Unit_Price_EGP,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,Courier,Expected_Delivery_Days,Actual_Delivery_Days,Delivery_Status,Returned,Return_Reason_Category,Return_Complaint_Text,Return_Request_Date,Refund_Method,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price_EGP,Weather,Season
0,ORD0000001,2025-01-01,13:35,C00012,Female,32,Miami,Miami,Store,Fashion,Women Clothing,F008,Basic Blouse,TrendHub,432.30,2,0.05,InstaPay,Walk-in,Weekend Promo,NaN,0,0,Picked up in store,No,NaN,NaN,NaT,NaN,4.5,85,Alex Local Factory,7,445.16,Sunny,Winter
1,ORD0000002,2025-01-01,14:00,C00022,Male,36,Smouha,Smouha,Store,Stationery & Books,Stationery,K001,Premium Notebook,Paperly,146.42,2,0.15,Card,Walk-in,Winter Sale,NaN,0,0,Picked up in store,No,NaN,NaN,NaT,NaN,4.5,92,Local Supplier,7,135.96,Sunny,Winter
2,ORD0000003,2025-01-01,15:00,C00445,Female,33,Victoria,Downtown Alexandria,Store,Electronics Accessories,Mobile Accessories,E006,Screen Protector,Coverly,133.38,1,0.00,Cash,Walk-in,No Campaign,NaN,0,0,Picked up in store,No,NaN,NaN,NaT,NaN,4.1,124,Cairo Distributor,10,150.79,Sunny,Winter
3,ORD0000004,2025-01-01,15:10,C00089,Male,31,Sidi Bishr,Sidi Bishr,Store,Fashion,Men Clothing,F006,Linen Shirt,NorthCoast,666.06,2,0.20,Cash,Walk-in,Winter Sale,NaN,0,0,Picked up in store,Yes,Damaged Packaging,الكرتونة كانت مفتوحة والتغليف متبهدل,2025-01-03,Store Credit,1.9,92,Cairo Textile Hub,7,623.85,Windy,Winter
4,ORD0000005,2025-01-01,15:40,C00959,Female,32,Sporting,Stanley,Instagram,Footwear,Sneakers,S001,White Sneakers,StepUp,1462.04,1,0.00,Card,Instagram Ads,No Campaign,DeltaShip,2,2,On time,No,NaN,NaN,NaT,NaN,4.9,77,Local Supplier,3,1589.89,Sunny,Winter

In [34]:
df.isna().sum()

Order_ID                          0
Order_Date                        0
Order_Time                        0
Customer_ID                       0
Customer_Gender                   0
Customer_Age                      0
Customer_Area                     0
Branch                            0
Sales_Channel                     0
Product_Domain                    0
Category                          0
Product_ID                        0
Product_Name                      0
Brand                             0
Unit_Price_EGP                    0
Quantity                          0
Discount_Percent                  0
Payment_Method                    0
Marketing_Source                  0
Campaign_Name                     0
Courier                        2566
Expected_Delivery_Days            0
Actual_Delivery_Days              0
Delivery_Status                   0
Returned                          0
Return_Reason_Category         5957
Return_Complaint_Text          5957
Return_Request_Date            5957
Refund_Method                  5957
Rating                            0
Stock_Available_Before_Sale       0
Supplier                          0
Lead_Time_Days                    0
Competitor_Price_EGP              0
Weather                           0
Season                            0
dtype: int64

In [35]:
# df.fillna(0, inplace=True)

In [36]:
df.isnull().sum()

Order_ID                          0
Order_Date                        0
Order_Time                        0
Customer_ID                       0
Customer_Gender                   0
Customer_Age                      0
Customer_Area                     0
Branch                            0
Sales_Channel                     0
Product_Domain                    0
Category                          0
Product_ID                        0
Product_Name                      0
Brand                             0
Unit_Price_EGP                    0
Quantity                          0
Discount_Percent                  0
Payment_Method                    0
Marketing_Source                  0
Campaign_Name                     0
Courier                        2566
Expected_Delivery_Days            0
Actual_Delivery_Days              0
Delivery_Status                   0
Returned                          0
Return_Reason_Category         5957
Return_Complaint_Text          5957
Return_Request_Date            5957
Refund_Method                  5957
Rating                            0
Stock_Available_Before_Sale       0
Supplier                          0
Lead_Time_Days                    0
Competitor_Price_EGP              0
Weather                           0
Season                            0
dtype: int64

In [37]:
df['Courier']

0                NaN
1                NaN
2                NaN
3                NaN
4          DeltaShip
            ...
6995             NaN
6996       DeltaShip
6997    Alex Courier
6998             NaN
6999       DeltaShip
Name: Courier, Length: 7000, dtype: object

In [38]:
df['Return_Reason_Category']

0                     NaN
1                     NaN
2                     NaN
3       Damaged Packaging
4                     NaN
              ...
6995    Damaged Packaging
6996                  NaN
6997                  NaN
6998                  NaN
6999                  NaN
Name: Return_Reason_Category, Length: 7000, dtype: object

In [39]:
df['Courier'].fillna("unknown", inplace=True)

In [40]:
df['Courier']

0            unknown
1            unknown
2            unknown
3            unknown
4          DeltaShip
            ...
6995         unknown
6996       DeltaShip
6997    Alex Courier
6998         unknown
6999       DeltaShip
Name: Courier, Length: 7000, dtype: object

In [45]:
print(df['Courier'].head(20))

0           unknown
1           unknown
2           unknown
3           unknown
4         DeltaShip
5           unknown
6     Flash Express
7     Flash Express
8           unknown
9         DeltaShip
10          unknown
11        DeltaShip
12        DeltaShip
13     Alex Courier
14          unknown
15     Alex Courier
16          unknown
17        DeltaShip
18        DeltaShip
19          unknown
Name: Courier, dtype: object

In [46]:
df['Courier'].str.upper()

0            UNKNOWN
1            UNKNOWN
2            UNKNOWN
3            UNKNOWN
4          DELTASHIP
            ...
6995         UNKNOWN
6996       DELTASHIP
6997    ALEX COURIER
6998         UNKNOWN
6999       DELTASHIP
Name: Courier, Length: 7000, dtype: object

In [50]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Time', 'Customer_ID',
       'Customer_Gender', 'Customer_Age', 'Customer_Area', 'Branch',
       'Sales_Channel', 'Product_Domain', 'Category', 'Product_ID',
       'Product_Name', 'Brand', 'Unit_Price_EGP', 'Quantity',
       'Discount_Percent', 'Payment_Method', 'Marketing_Source',
       'Campaign_Name', 'Courier', 'Expected_Delivery_Days',
       'Actual_Delivery_Days', 'Delivery_Status', 'Returned',
       'Return_Reason_Category', 'Return_Complaint_Text',
       'Return_Request_Date', 'Refund_Method', 'Rating',
       'Stock_Available_Before_Sale', 'Supplier', 'Lead_Time_Days',
       'Competitor_Price_EGP', 'Weather', 'Season'],
      dtype='object')

In [62]:
df.columns = (df.columns
.str.replace(' ', '_')
.str.replace('Courier', 'sherket_elsha7n')
)

## to make all coulmn names good

In [53]:
df.columns

Index(['Order_ID', 'Order_Date', 'Order_Time', 'Customer_ID',
       'Customer_Gender', 'Customer_Age', 'Customer_Area', 'Branch',
       'Sales_Channel', 'Product_Domain', 'Category', 'Product_ID',
       'Product_Name', 'Brand', 'Unit_Price_EGP', 'Quantity',
       'Discount_Percent', 'Payment_Method', 'Marketing_Source',
       'Campaign_Name', 'sherket_elsha7n', 'Expected_Delivery_Days',
       'Actual_Delivery_Days', 'Delivery_Status', 'Returned',
       'Return_Reason_Category', 'Return_Complaint_Text',
       'Return_Request_Date', 'Refund_Method', 'Rating',
       'Stock_Available_Before_Sale', 'Supplier', 'Lead_Time_Days',
       'Competitor_Price_EGP', 'Weather', 'Season'],
      dtype='object')

In [54]:
df['sherket_elsha7n']

0            unknown
1            unknown
2            unknown
3            unknown
4          DeltaShip
            ...
6995         unknown
6996       DeltaShip
6997    Alex Courier
6998         unknown
6999       DeltaShip
Name: sherket_elsha7n, Length: 7000, dtype: object

In [60]:
df['Customer_Gender'] = df['Customer_Gender'].replace({'Male': 'M', 'Female': 'F'})  #standardize

In [61]:
df['Customer_Gender']

0       F
1       M
2       F
3       M
4       F
       ..
6995    F
6996    F
6997    M
6998    F
6999    M
Name: Customer_Gender, Length: 7000, dtype: object

In [63]:
df.head()

,Order_ID,Order_Date,Order_Time,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Branch,Sales_Channel,Product_Domain,Category,Product_ID,Product_Name,Brand,Unit_Price_EGP,Quantity,Discount_Percent,Payment_Method,Marketing_Source,Campaign_Name,sherket_elsha7n,Expected_Delivery_Days,Actual_Delivery_Days,Delivery_Status,Returned,Return_Reason_Category,Return_Complaint_Text,Return_Request_Date,Refund_Method,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price_EGP,Weather,Season
0,ORD0000001,2025-01-01,13:35,C00012,F,32,Miami,Miami,Store,Fashion,Women Clothing,F008,Basic Blouse,TrendHub,432.30,2,0.05,InstaPay,Walk-in,Weekend Promo,unknown,0,0,Picked up in store,No,NaN,NaN,NaT,NaN,4.5,85,Alex Local Factory,7,445.16,Sunny,Winter
1,ORD0000002,2025-01-01,14:00,C00022,M,36,Smouha,Smouha,Store,Stationery & Books,Stationery,K001,Premium Notebook,Paperly,146.42,2,0.15,Card,Walk-in,Winter Sale,unknown,0,0,Picked up in store,No,NaN,NaN,NaT,NaN,4.5,92,Local Supplier,7,135.96,Sunny,Winter
2,ORD0000003,2025-01-01,15:00,C00445,F,33,Victoria,Downtown Alexandria,Store,Electronics Accessories,Mobile Accessories,E006,Screen Protector,Coverly,133.38,1,0.00,Cash,Walk-in,No Campaign,unknown,0,0,Picked up in store,No,NaN,NaN,NaT,NaN,4.1,124,Cairo Distributor,10,150.79,Sunny,Winter
3,ORD0000004,2025-01-01,15:10,C00089,M,31,Sidi Bishr,Sidi Bishr,Store,Fashion,Men Clothing,F006,Linen Shirt,NorthCoast,666.06,2,0.20,Cash,Walk-in,Winter Sale,unknown,0,0,Picked up in store,Yes,Damaged Packaging,الكرتونة كانت مفتوحة والتغليف متبهدل,2025-01-03,Store Credit,1.9,92,Cairo Textile Hub,7,623.85,Windy,Winter
4,ORD0000005,2025-01-01,15:40,C00959,F,32,Sporting,Stanley,Instagram,Footwear,Sneakers,S001,White Sneakers,StepUp,1462.04,1,0.00,Card,Instagram Ads,No Campaign,DeltaShip,2,2,On time,No,NaN,NaN,NaT,NaN,4.9,77,Local Supplier,3,1589.89,Sunny,Winter

In [64]:
df['Actual_Delivery_Days'] = df['Actual_Delivery_Days'].astype('float64')

In [67]:
dc = pd.read_csv("D:/TECHTRECK/outlier_cleaning_sales_raw.csv")

In [68]:
dc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2220 entries, 0 to 2219
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        2220 non-null   object
 1   order_date      2220 non-null   object
 2   customer_id     2220 non-null   object
 3   city            2192 non-null   object
 4   region          2220 non-null   object
 5   segment         2220 non-null   object
 6   channel         2220 non-null   object
 7   category        2220 non-null   object
 8   product         2220 non-null   object
 9   quantity        2220 non-null   int64
 10  unit_price      2203 non-null   object
 11  discount_pct    2220 non-null   float64
 12  shipping_cost   2220 non-null   float64
 13  revenue         2220 non-null   float64
 14  cost            2220 non-null   float64
 15  profit          2220 non-null   float64
 16  rating          2178 non-null   float64
 17  delivery_days   2220 non-null   int64
 18  returned        2220 non-null   object
 19  payment_method  2220 non-null   object
 20  issue_notes     268 non-null    object
dtypes: float64(6), int64(2), object(13)
memory usage: 364.3+ KB

In [70]:
dc.head()

,order_id,order_date,customer_id,city,region,segment,channel,category,product,quantity,unit_price,discount_pct,shipping_cost,revenue,cost,profit,rating,delivery_days,returned,payment_method,issue_notes
0,ORD-100001,2026-06-13,CUST-1214,Cairo,Greater Cairo,Corporate,Online,Electronics,Laptop Pro,3,25116.59,0.121,168.01,66210.87,58772.82,7270.04,3.0,3,No,Installments,NaN
1,ORD-100002,2026-02-26,CUST-1309,Giza,Greater Cairo,Consumer,Partner,Grocery,Olive Oil,3,419.54,0.118,70.99,1109.93,981.72,57.22,2.0,4,No,Wallet,NaN
2,ORD-100003,2026-03-09,CUST-1437,Tanta,Delta,Corporate,Retail,Beauty,Makeup Kit,1,899.83,0.195,50.12,724.43,521.90,152.41,3.0,5,No,Card,NaN
3,ORD-100004,2026-03-01,CUST-1083,Zagazig,Delta,Consumer,Online,Grocery,Olive Oil,2,456.62,0.154,73.81,772.71,712.33,-13.43,4.0,4,No,Cash,NaN
4,ORD-100005,2026-04-29,CUST-1108,Giza,Greater Cairo,Small Business,Retail,Fashion,Backpack,4,914.78,0.000,85.00,3659.12,2268.65,1305.47,3.0,4,No,Wallet,NaN

In [74]:
dc['payment_method'] = dc['payment_method'].replace({'Wallet': 'Instapay', 'Card': 'Credit'})  #standardize

In [81]:
dc['payment_method']

0       Installments
1           Instapay
2             Credit
3               Cash
4           Instapay
            ...
2215        Instapay
2216    Installments
2217    Installments
2218        Instapay
2219            Cash
Name: payment_method, Length: 2220, dtype: object

In [87]:
dc['sh7n'] = dc['shipping_cost'].fillna(dc['payment_method'])

In [88]:
dc['sh7n'].head(20)

0     168.01
1      70.99
2      50.12
3      73.81
4      85.00
5     280.08
6      77.51
7     212.14
8     317.83
9     167.91
10     45.21
11    211.07
12     49.98
13    238.42
14    131.99
15     48.34
16     71.20
17     78.71
18     65.61
19     44.30
Name: sh7n, dtype: float64

In [89]:
dc.columns

Index(['order_id', 'order_date', 'customer_id', 'city', 'region', 'segment',
       'channel', 'category', 'product', 'quantity', 'unit_price',
       'discount_pct', 'shipping_cost', 'revenue', 'cost', 'profit', 'rating',
       'delivery_days', 'returned', 'payment_method', 'issue_notes', 'sh7n'],
      dtype='object')

In [98]:
dc['customer_id'] = dc['customer_id'].drop_duplicates(keep= False)

In [101]:
dcc = dc.copy()

In [108]:
print(dcc.info())
print("-------------55-------")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2220 entries, 0 to 2219
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        2220 non-null   object
 1   order_date      2220 non-null   object
 2   customer_id     448 non-null    object
 3   city            2192 non-null   object
 4   region          2220 non-null   object
 5   segment         2220 non-null   object
 6   channel         2220 non-null   object
 7   category        2220 non-null   object
 8   product         2220 non-null   object
 9   quantity        2220 non-null   int64
 10  unit_price      2203 non-null   object
 11  discount_pct    2220 non-null   float64
 12  shipping_cost   2220 non-null   float64
 13  revenue         2220 non-null   float64
 14  cost            2220 non-null   float64
 15  profit          2220 non-null   float64
 16  rating          2178 non-null   float64
 17  delivery_days   2220 non-null   int64
 18  returned        2220 non-null   object
 19  payment_method  2220 non-null   object
 20  issue_notes     268 non-null    object
 21  sh7n            2220 non-null   float64
dtypes: float64(7), int64(2), object(13)
memory usage: 381.7+ KB
None
-------------55-------

In [109]:
print(dc.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2220 entries, 0 to 2219
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        2220 non-null   object
 1   order_date      2220 non-null   object
 2   customer_id     448 non-null    object
 3   city            2192 non-null   object
 4   region          2220 non-null   object
 5   segment         2220 non-null   object
 6   channel         2220 non-null   object
 7   category        2220 non-null   object
 8   product         2220 non-null   object
 9   quantity        2220 non-null   int64
 10  unit_price      2203 non-null   object
 11  discount_pct    2220 non-null   float64
 12  shipping_cost   2220 non-null   float64
 13  revenue         2220 non-null   float64
 14  cost            2220 non-null   float64
 15  profit          2220 non-null   float64
 16  rating          2178 non-null   float64
 17  delivery_days   2220 non-null   int64
 18  returned        2220 non-null   object
 19  payment_method  2220 non-null   object
 20  issue_notes     268 non-null    object
 21  sh7n            2220 non-null   float64
dtypes: float64(7), int64(2), object(13)
memory usage: 381.7+ KB
None

In [112]:
dc.head()

,order_id,order_date,customer_id,city,region,segment,channel,category,product,quantity,unit_price,discount_pct,shipping_cost,revenue,cost,profit,rating,delivery_days,returned,payment_method,issue_notes,sh7n
0,ORD-100001,2026-06-13,CUST-1214,Cairo,Greater Cairo,Corporate,Online,Electronics,Laptop Pro,3,25116.59,0.121,168.01,66210.87,58772.82,7270.04,3.0,3,No,Installments,NaN,168.01
1,ORD-100002,2026-02-26,CUST-1309,Giza,Greater Cairo,Consumer,Partner,Grocery,Olive Oil,3,419.54,0.118,70.99,1109.93,981.72,57.22,2.0,4,No,Instapay,NaN,70.99
2,ORD-100003,2026-03-09,CUST-1437,Tanta,Delta,Corporate,Retail,Beauty,Makeup Kit,1,899.83,0.195,50.12,724.43,521.90,152.41,3.0,5,No,Credit,NaN,50.12
3,ORD-100004,2026-03-01,CUST-1083,Zagazig,Delta,Consumer,Online,Grocery,Olive Oil,2,456.62,0.154,73.81,772.71,712.33,-13.43,4.0,4,No,Cash,NaN,73.81
4,ORD-100005,2026-04-29,CUST-1108,Giza,Greater Cairo,Small Business,Retail,Fashion,Backpack,4,914.78,0.000,85.00,3659.12,2268.65,1305.47,3.0,4,No,Instapay,NaN,85.00

In [124]:
dc['region']

0       Greater Cairo
1       Greater Cairo
2               Delta
3               Delta
4       Greater Cairo
            ...
2215    Greater Cairo
2216    Greater Cairo
2217            Canal
2218      North Coast
2219            Delta
Name: region, Length: 2220, dtype: object

In [128]:
dc['region'] = dc['region'].str.replace(' ', '_')

In [129]:
dc['region']

0       Greater_Cairo
1       Greater_Cairo
2               Delta
3               Delta
4       Greater_Cairo
            ...
2215    Greater_Cairo
2216    Greater_Cairo
2217            Canal
2218      North_Coast
2219            Delta
Name: region, Length: 2220, dtype: object

## HOW TO DETECT OUTLIERS

In [139]:
Q1 = dc['quantity'].quantile(0.25)
Q3 = dc['quantity'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlierss = dc[(dc['quantity'] < lower_bound) | (dc['quantity'] > upper_bound)]
print(outlierss)

        order_id  order_date customer_id        city         region  \
597   ORD-100598  2026-04-02         NaN       Tanta          Delta
658   ORD-100659  2026-01-25         NaN    Mansoura          Delta
912   ORD-100913  2026-01-10         NaN       Cairo  Greater_Cairo
1090  ORD-101091  2026-05-03         NaN        Giza  Greater_Cairo
1258  ORD-101259  2026-02-25         NaN    Mansoura          Delta
1300  ORD-101301  2026-01-16         NaN  Alexandria    North_Coast
1476  ORD-101477  2026-01-01         NaN        Suez          Canal
1531  ORD-101532  2026-05-12         NaN    Mansoura          Delta
1576  ORD-101577  2026-04-02         NaN  Alexandria    North_Coast
1648  ORD-101649  2026-06-27         NaN       Cairo  Greater_Cairo
1800  ORD-101801  2026-02-17         NaN       Tanta          Delta
1808  ORD-101809  2026-02-08         NaN       Aswan    Upper_Egypt
2153  ORD-102154  2026-04-20         NaN       Tanta          Delta
2217  ORD-101115  2026-03-12         NaN        Suez          Canal
2219  ORD-100410  2026-03-11         NaN       Tanta          Delta

             segment channel     category           product  quantity  \
597   Small Business  Retail    Furniture          Sofa Bed        25
658         Consumer  Retail    Furniture     Standing Desk        25
912        Corporate  Online  Electronics        Power Bank        40
1090        Consumer  Retail      Grocery      Coffee Beans        40
1258        Consumer  Retail      Fashion            Hoodie        25
1300        Consumer  Online       Beauty        Skin Serum        55
1476       Corporate  Online  Electronics      Smartphone X        80
1531        Consumer  Retail  Electronics        Power Bank        40
1576       Corporate  Online      Grocery        Dates Pack        40
1648  Small Business  Retail      Fashion            Jacket        25
1800        Consumer  Online  Electronics        Power Bank        40
1808        Consumer  Retail      Fashion          Backpack        55
2153        Consumer  Online  Electronics  Wireless Headset        25
2217        Consumer  Online  Electronics     Standing Desk         9
2219     Home Office  Social    Furniture          Backpack         9

     unit_price  discount_pct  shipping_cost     revenue      cost    profit  \
597    11981.85         0.000         151.16   299546.25  28037.53   7756.86
658     9195.22         0.000         274.44   229880.50  55171.32  18116.00
912      742.93         0.155          81.13    25111.03    861.80    313.14
1090     220.32         0.205          87.73     7006.18    330.48    -67.70
1258    1217.78         0.000          63.38    30444.50   1339.56   1032.62
1300     799.48         0.225         130.61    34077.83   1662.92    683.66
1476   18397.69         0.085         250.71  1346710.91  60344.42   6707.99
1531     866.95         0.000          58.78    34678.00   1005.66    669.46
1576     211.25         0.078          82.31     7790.90    338.00    -30.76
1648    2419.32         0.228          67.59    46692.88   3096.73    570.79
1800     837.45         0.243          44.61    25357.99    485.72    103.86
1808     819.77         0.144         121.08    38594.77   2033.03    652.94
2153    2041.74         0.000         162.13    51043.50   7962.79   4125.52
2217     514.32         0.137         194.19     3551.11   2386.44    970.48
2219   10107.35         0.101         159.37    72726.53  63069.86   9497.30

      rating  delivery_days returned payment_method  \
597      5.0              3       No           Cash
658      3.0              5       No         Credit
912      3.0              3       No   Installments
1090     5.0              3       No           Cash
1258     4.0              5       No         Credit
1300     3.0              2       No         Credit
1476     5.0              2       No   Installments
1531     5.0              1       No           Cash
1576     3.0              1       No           Cash
1648     5.0              5       No   Installments
1800     2.0              3       No  Bank Transfer
1808     3.0              1       No         Credit
2153     3.0              1       No         Credit
2217     5.0              3       No   Installments
2219     4.0              3       No           Cash

                                    issue_notes    sh7n
597                          quantity outlier;   151.16
658                          quantity outlier;   274.44
912                          quantity outlier;    81.13
1090                         quantity outlier;    87.73
1258                         quantity outlier;    63.38
1300                         quantity outlier;   130.61
1476                         quantity outlier;   250.71
1531                         quantity outlier;    58.78
1576                         quantity outlier;    82.31
1648                         quantity outlier;    67.59
1800                         quantity outlier;    44.61
1808                         quantity outlier;   121.08
2153                         quantity outlier;   162.13
2217  duplicate order_id with changed product;   194.19
2219  duplicate order_id with changed product;   159.37

In [137]:
Q11 = dc['profit'].quantile(0.25)
Q33 = dc['profit'].quantile(0.75)
IQR = Q33 - Q11
lower_bound = Q11 - 1.5 * IQR
upper_bound = Q33 + 1.5 * IQR

outliers = dc[(dc['profit'] < lower_bound) | (dc['profit'] > upper_bound)]
print(outliers)

        order_id  order_date customer_id        city         region  \
0     ORD-100001  2026-06-13   CUST-1214       Cairo  Greater_Cairo
7     ORD-100008  2026-03-10   CUST-1430       Tanta          Delta
8     ORD-100009  2026-06-13   CUST-1043  Alexandria    North_Coast
13    ORD-100014  2026-05-21   CUST-1001       Cairo  Greater_Cairo
43    ORD-100044  2026-01-04   CUST-1076  Alexandria    North_Coast
...          ...         ...         ...         ...            ...
2193  ORD-102194  2026-01-28         NaN    Mansoura          Delta
2198  ORD-102199  2026-05-27         NaN  Alexandria    North_Coast
2211  ORD-100478  2026-01-12         NaN       Cairo  Greater_Cairo
2216  ORD-100423  2026-01-06         NaN       Cairo  Greater_Cairo
2219  ORD-100410  2026-03-11         NaN       Tanta          Delta

          segment channel     category       product  quantity unit_price  \
0       Corporate  Online  Electronics    Laptop Pro         3   25116.59
7        Consumer  Online  Electronics    Laptop Pro         6   22204.34
8        Consumer  Online  Electronics    Laptop Pro         3   22367.53
13      Corporate  Retail  Electronics    Laptop Pro         6   25650.01
43       Consumer  Online  Electronics    Laptop Pro         1   22348.55
...           ...     ...          ...           ...       ...        ...
2193    Corporate  Retail  Electronics  Smartphone X         3        NaN
2198     Consumer  Retail      Fashion        Jacket         8    2476.17
2211     Consumer  Online  Electronics        Hoodie         5   27819.67
2216  Home Office  Online  Electronics      Sofa Bed         6   21336.31
2219  Home Office  Social    Furniture      Backpack         9   10107.35

      discount_pct  shipping_cost    revenue       cost    profit  rating  \
0            0.121         168.01   66210.87   58772.82   7270.04     3.0
7            0.179         212.14  109390.61  103916.31   5262.16     5.0
8            0.142         317.83   57544.56   52340.02   4886.71     5.0
13           0.125         238.42  134733.99  120042.05  14453.52     4.0
43           0.000         205.67   22348.55   17431.87   4711.01     4.0
...            ...            ...        ...        ...       ...     ...
2193         0.083         164.31   56729.19   50738.29   5826.59     5.0
2198         0.112         125.59   17595.10   12677.99   4791.52     4.0
2211         0.100         227.58  100161.57   86797.37  13136.62     4.0
2216         0.177         180.25   87831.02   83211.61   4439.16     5.0
2219         0.101         159.37   72726.53   63069.86   9497.30     4.0

      delivery_days returned payment_method  \
0                 3       No   Installments
7                 2       No       Instapay
8                 3       No         Credit
13                2       No  Bank Transfer
43                2       No           Cash
...             ...      ...            ...
2193              2       No   Installments
2198              2       No  Bank Transfer
2211              1       No       Instapay
2216              3       No   Installments
2219              3       No           Cash

                                    issue_notes    sh7n
0                                           NaN  168.01
7                                           NaN  212.14
8                                           NaN  317.83
13                                          NaN  238.42
43                                          NaN  205.67
...                                         ...     ...
2193                            missing price;   164.31
2198                                        NaN  125.59
2211  duplicate order_id with changed product;   227.58
2216  duplicate order_id with changed product;   180.25
2219  duplicate order_id with changed product;   159.37

[231 rows x 22 columns]

In [138]:
fig = px.histogram(outliers, x='profit', title="Histogram of Profit")
fig.show()

In [140]:
fig = px.histogram(outlierss, x='quantity', title="Histogram of Quantity")
fig.show()

In [141]:
from scipy import stats
dc['z_score'] = stats.zscore(dc['profit'])

In [142]:
print(dc[['profit', 'z_score']].head(10))

    profit   z_score
0  7270.04  1.633417
1    57.22 -0.476891
2   152.41 -0.449040
3   -13.43 -0.497561
4  1305.47 -0.111681
5  2835.73  0.336038
6  1059.28 -0.183711
7  5262.16  1.045957
8  4886.71  0.936109
9  1204.96 -0.141088

In [143]:
figg = px.histogram(dc[['profit', 'z_score']], x='profit', title="Histogram of Profit")
figg.show()

In [144]:
z = (dc['profit'] - dc['profit'].mean()) / dc['profit'].std()
dc['z_outlier'] = z.abs() > 3

In [145]:
figgg = px.histogram(z, x='profit', title="Histogram of Profit")
figgg.show()