In [1]:
print("hello iam zoz")

hello iam zoz

In [3]:
print("this is the first session in AI")

this is the first session in AI

In [5]:
x = 10
y = 20
print(f'SUM OF X ,Y IS {x+y}')

SUM OF X ,Y IS 30

In [6]:
name = 'ziad'
print(f'HELLO IAM {name}')

HELLO IAM ziad

In [7]:
x = 3 #int
y = 3.5 #double or float
z = True #boolean
t = 'ziad'#string

In [9]:
x = 10
x = x + 5 # update
print(x)

15

In [10]:
x = 5
x+=1 #increment == x++
print(x)

6

In [11]:
x = 5
x*=2 #increment == x * 2
print(x)

10

In [16]:
age = 20
if age >= 15 :
  print('u r teenager')
elif age < 10 :
  print('u r still young')
else :
  print('how old r u ??')
  new_age = input('tell me now ')

u r teenager

In [28]:
# 3 var (salary , pname , pid)

salary1 = 20000
pname1 = "pc"  # item 1
pid1 = 1

salary2 = 15000
pname2 = "laptop" # item 2
pid2 = 2

salary3 = 2000
pname3 = "iphone 4s" # item 3
pid3 = 3

print(f"id: {pid1}, name: {pname1}")
print(f"total salary: {salary1}")

if salary1 > 3000:
    print("High")
else:
    print("Low")

print(f"id: {pid2}, name: {pname2}")
print(f"total salary: {salary2}")

if salary2 > 3000:
    print("High")
else:
    print("Low")

print(f"id: {pid3}, name: {pname3}")
print(f"total salary: {salary3}")

if salary3 > 3000:
    print("High")
else:
    print("Low")

id: 1, name: pc
total salary: 20000
High
id: 2, name: laptop
total salary: 15000
High
id: 3, name: iphone 4s
total salary: 2000
Low

In [29]:
x = 2026
y = str(x) # type casting
print(y)
print(type(y))

2026
<class 'str'>

In [30]:
info = ['ziad' , 20 , 'benha', 'AI']
print(info[0])

ziad

In [34]:
info.append("BNU") # add at the end of list
info.extend(['CS', '3rd-year'])  # add more than one thing separitly
info.insert(3, 'QALYOBIA') # add into spicfic place


for i in info:
  print(i)

ziad
20
benha
QALYOBIA
AI
BNU
CS
3rd-year

In [43]:
jobs = ["software engineer", "doctor", "ML Engineer"]
jobs.append("footballer")
jobs.insert(3, 'scientest')
jobs.extend(["civel Engineer", "architect", "AI Engineer"])
print(jobs)

['software engineer', 'doctor', 'ML Engineer', 'scientest', 'footballer', 'civel Engineer', 'architect', 'AI Engineer']

In [44]:
jobs.remove('footballer')
jobs.pop(3)

'scientest'

In [45]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9

In [46]:
for i in jobs:
  print(i)

software engineer
doctor
ML Engineer
civel Engineer
architect
AI Engineer

In [48]:
for i in range(10,0,-1) : #step backward start from 10 to end
  print(i)

10
9
8
7
6
5
4
3
2
1

In [50]:
print('----------------------------------------------------')
print('end of p0 basics')
print('----------------------------------------------------')

----------------------------------------------------
end of p0 basics
----------------------------------------------------

In [59]:
import numpy as np
import pandas as pd

df = pd.read_excel('/Raw_Retail_Sales_Dataset_5000.xlsx')

In [60]:
df

,Order_ID,Order_Date,Order_Time,Branch,Sales_Channel,Customer_ID,Customer_Gender,Customer_Age,Customer_Area,Product_ID,...,Campaign_Name,Returned,Return_Reason,Rating,Stock_Available_Before_Sale,Supplier,Lead_Time_Days,Competitor_Price,Weather,Season
0,ORD000001,2025-04-25,21:05,Smouha,TikTok Shop,C0433,Male,19,Smouha,P001,...,No Campaign,No,NaN,3.9,188,In-house,5,214.83,Rainy,Spring
1,ORD000002,2025-01-07,14:10,Stanley,WhatsApp,C0105,Male,42,Smouha,P025,...,Winter Sale,No,NaN,4.5,191,In-house,14,729.63,Hot,Winter
2,ORD000003,2025-03-22,15:15,Smouha,Store,C0678,Male,36,Smouha,P018,...,Winter Sale,No,NaN,3.6,218,Imported Batch,5,497.25,Cloudy,Spring
3,ORD000004,2025-10-01,12:15,Miami,Instagram,C0389,Female,58,Victoria,P023,...,Black Friday,No,NaN,4.4,63,Local Supplier,7,323.06,Sunny,Autumn
4,ORD000005,2025-08-05,20:50,Downtown Alexandria,Instagram,C0147,Female,26,Stanley,P030,...,Ramadan Offers,No,NaN,3.6,154,In-house,7,647.59,Cloudy,Summer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,ORD004996,2026-03-23,17:30,Miami,Website,C0033,Male,64,Gleem,P019,...,Black Friday,No,NaN,3.2,115,In-house,10,233.92,Rainy,Spring
4996,ORD004997,2026-05-24,12:15,Miami,Store,C0406,Male,36,Smouha,P007,...,Summer Sale,No,NaN,4.7,147,Imported Batch,3,457.58,Cloudy,Spring
4997,ORD004998,2025-09-21,13:15,Stanley,Instagram,C0334,Female,35,Smouha,P005,...,Summer Sale,No,NaN,3.0,241,Cairo Distributor,10,838.79,Windy,Autumn
4998,ORD004999,2026-02-02,10:50,Miami,TikTok Shop,C0778,Male,34,Miami,P018,...,No Campaign,No,NaN,4.7,210,In-house,5,558.30,Windy,Winter
4999,ORD005000,2026-03-06,22:15,Miami,WhatsApp,C0121,Male,28,Louran,P016,...,Black Friday,No,NaN,2.7,118,Imported Batch,5,348.32,Hot,Spring

In [64]:
print("first 5 rows:")
print(df.head())

print("last 5 rows:")
print(df.tail())

print("Info:")
print(df.info())

print("Is null sum:")
print(df.isnull().sum())

first 5 rows:
    Order_ID  Order_Date Order_Time               Branch Sales_Channel  \
0  ORD000001  2025-04-25      21:05               Smouha   TikTok Shop
1  ORD000002  2025-01-07      14:10              Stanley      WhatsApp
2  ORD000003  2025-03-22      15:15               Smouha         Store
3  ORD000004  2025-10-01      12:15                Miami     Instagram
4  ORD000005  2025-08-05      20:50  Downtown Alexandria     Instagram

  Customer_ID Customer_Gender  Customer_Age Customer_Area Product_ID  ...  \
0       C0433            Male            19        Smouha       P001  ...
1       C0105            Male            42        Smouha       P025  ...
2       C0678            Male            36        Smouha       P018  ...
3       C0389          Female            58      Victoria       P023  ...
4       C0147          Female            26       Stanley       P030  ...

    Campaign_Name Returned Return_Reason  Rating  Stock_Available_Before_Sale  \
0     No Campaign       No           NaN     3.9                          188
1     Winter Sale       No           NaN     4.5                          191
2     Winter Sale       No           NaN     3.6                          218
3    Black Friday       No           NaN     4.4                           63
4  Ramadan Offers       No           NaN     3.6                          154

         Supplier Lead_Time_Days Competitor_Price Weather  Season
0        In-house              5           214.83   Rainy  Spring
1        In-house             14           729.63     Hot  Winter
2  Imported Batch              5           497.25  Cloudy  Spring
3  Local Supplier              7           323.06   Sunny  Autumn
4        In-house              7           647.59  Cloudy  Summer

[5 rows x 28 columns]
last 5 rows:
       Order_ID  Order_Date Order_Time   Branch Sales_Channel Customer_ID  \
4995  ORD004996  2026-03-23      17:30    Miami       Website       C0033
4996  ORD004997  2026-05-24      12:15    Miami         Store       C0406
4997  ORD004998  2025-09-21      13:15  Stanley     Instagram       C0334
4998  ORD004999  2026-02-02      10:50    Miami   TikTok Shop       C0778
4999  ORD005000  2026-03-06      22:15    Miami      WhatsApp       C0121

     Customer_Gender  Customer_Age Customer_Area Product_ID  ...  \
4995            Male            64         Gleem       P019  ...
4996            Male            36        Smouha       P007  ...
4997          Female            35        Smouha       P005  ...
4998            Male            34         Miami       P018  ...
4999            Male            28        Louran       P016  ...

     Campaign_Name Returned Return_Reason  Rating  \
4995  Black Friday       No           NaN     3.2
4996   Summer Sale       No           NaN     4.7
4997   Summer Sale       No           NaN     3.0
4998   No Campaign       No           NaN     4.7
4999  Black Friday       No           NaN     2.7

      Stock_Available_Before_Sale           Supplier Lead_Time_Days  \
4995                          115           In-house             10
4996                          147     Imported Batch              3
4997                          241  Cairo Distributor             10
4998                          210           In-house              5
4999                          118     Imported Batch              5

     Competitor_Price Weather  Season
4995           233.92   Rainy  Spring
4996           457.58  Cloudy  Spring
4997           838.79   Windy  Autumn
4998           558.30   Windy  Winter
4999           348.32     Hot  Spring

[5 rows x 28 columns]
Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order_ID                     5000 non-null   object
 1   Order_Date                   5000 non-null   object
 2   Order_Time                   5000 non-null   object
 3   Branch                       5000 non-null   object
 4   Sales_Channel                5000 non-null   object
 5   Customer_ID                  5000 non-null   object
 6   Customer_Gender              5000 non-null   object
 7   Customer_Age                 5000 non-null   int64
 8   Customer_Area                5000 non-null   object
 9   Product_ID                   5000 non-null   object
 10  Product_Name                 5000 non-null   object
 11  Category                     5000 non-null   object
 12  Brand                        5000 non-null   object
 13  Unit_Price                   5000 non-null   float64
 14  Quantity                     5000 non-null   int64
 15  Discount_Percent             5000 non-null   float64
 16  Payment_Method               5000 non-null   object
 17  Marketing_Source             5000 non-null   object
 18  Campaign_Name                5000 non-null   object
 19  Returned                     5000 non-null   object
 20  Return_Reason                318 non-null    object
 21  Rating                       5000 non-null   float64
 22  Stock_Available_Before_Sale  5000 non-null   int64
 23  Supplier                     5000 non-null   object
 24  Lead_Time_Days               5000 non-null   int64
 25  Competitor_Price             5000 non-null   float64
 26  Weather                      5000 non-null   object
 27  Season                       5000 non-null   object
dtypes: float64(4), int64(4), object(20)
memory usage: 1.1+ MB
None
Is null sum:
Order_ID                          0
Order_Date                        0
Order_Time                        0
Branch                            0
Sales_Channel                     0
Customer_ID                       0
Customer_Gender                   0
Customer_Age                      0
Customer_Area                     0
Product_ID                        0
Product_Name                      0
Category                          0
Brand                             0
Unit_Price                        0
Quantity                          0
Discount_Percent                  0
Payment_Method                    0
Marketing_Source                  0
Campaign_Name                     0
Returned                          0
Return_Reason                  4682
Rating                            0
Stock_Available_Before_Sale       0
Supplier                          0
Lead_Time_Days                    0
Competitor_Price                  0
Weather                           0
Season                            0
dtype: int64

In [62]:
df['Return_Reason'].head(60)

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
5               NaN
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
13              NaN
14              NaN
15              NaN
16     Changed Mind
17              NaN
18              NaN
19              NaN
20              NaN
21              NaN
22              NaN
23              NaN
24              NaN
25              NaN
26              NaN
27              NaN
28              NaN
29              NaN
30              NaN
31              NaN
32              NaN
33            Other
34              NaN
35              NaN
36              NaN
37              NaN
38              NaN
39              NaN
40              NaN
41       Wrong Size
42              NaN
43              NaN
44              NaN
45              NaN
46              NaN
47              NaN
48              NaN
49              NaN
50              NaN
51              NaN
52    Quality Issue
53              NaN
54              NaN
55              NaN
56              NaN
57              NaN
58              NaN
59              NaN
Name: Return_Reason, dtype: object